#!/usr/bin/env bash
#
# Re-derive src/firmware/golden/*.bin from the real loadp2, so the committed
# traces can be proven current rather than merely trusted.
#
#   tools/regen-loadp2-goldens.sh --check    # fail if committed goldens drifted
#   tools/regen-loadp2-goldens.sh            # overwrite them
#
# Builds loadp2 from source into a cache dir. The released macOS binary cannot
# be used: osint_linux.c calls IOSSIOSPEED under #ifdef MACOSX, which always
# fails on a PTY. Compiling without -DMACOSX takes the plain termios path, which
# a PTY accepts; the protocol code being compared is identical either way.
#
# Requires: git, a C compiler, python3. Not run in CI — the committed goldens
# are what CI checks against (see conformance.test.ts). Run this when bumping
# the loadp2 revision we claim conformance with.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
GOLDEN="$HERE/../src/firmware/golden"
CACHE="${LOADP2_CACHE:-${TMPDIR:-/tmp}/mad-loadp2-golden}"
LOADP2_REV="${LOADP2_REV:-master}"

check=0
[[ "${1:-}" == "--check" ]] && check=1

if [[ ! -x "$CACHE/loadp2_posix" ]]; then
  echo "building loadp2 ($LOADP2_REV) into $CACHE"
  rm -rf "$CACHE"
  git clone --quiet --depth 1 --branch "$LOADP2_REV" https://github.com/totalspectrum/loadp2 "$CACHE"
  # flash_stub.h is generated by a spin2 compiler we don't have. It is only
  # referenced by the two-stage -FLASH path, which single-stage never reaches.
  printf 'unsigned char flash_stub_bin[]={0};\nunsigned int flash_stub_bin_len=0;\n' > "$CACHE/flash_stub.h"
  ( cd "$CACHE" && cc -O1 -o loadp2_posix loadp2.c osint_linux.c loadelf.c u9fs/*.c -I. -Iu9fs )
fi
echo "loadp2: $("$CACHE/loadp2_posix" -? 2>&1 | head -1)"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

# Keep in step with CASES in conformance.test.ts.
declare -a NAMES=(tiny4 chunk128 partial300 exact1024)
declare -a SIZES=(4 128 300 1024)

status=0
for i in "${!NAMES[@]}"; do
  name="${NAMES[$i]}"; size="${SIZES[$i]}"
  # Same generator as testImage() in conformance.test.ts.
  python3 -c "open('$work/$name.bin','wb').write(bytes(((i*7)&0xff) for i in range($size)))"
  for mode in ram flash; do
    flags=(-SINGLE); [[ "$mode" == flash ]] && flags+=(-FLASH)
    python3 "$HERE/capture-loadp2-golden.py" \
      "$CACHE/loadp2_posix" "$work/$name.bin" "$work/$name.$mode.trace" "${flags[@]}" >/dev/null
    target="$GOLDEN/$name.$mode.bin"
    if (( check )); then
      if cmp -s "$work/$name.$mode.trace" "$target"; then
        echo "  ok      $name.$mode.bin"
      else
        echo "  DRIFTED $name.$mode.bin"
        cmp "$work/$name.$mode.trace" "$target" || true
        status=1
      fi
    else
      cp "$work/$name.$mode.trace" "$target"
      echo "  wrote   $name.$mode.bin ($(wc -c < "$target" | tr -d ' ') bytes)"
    fi
  done
done

if (( check && status )); then
  echo
  echo "Committed goldens no longer match this loadp2. Either loadp2 changed its"
  echo "wire format (rerun without --check and review the diff carefully), or the"
  echo "capture harness regressed."
fi
exit $status
