/**
 * @file protoemb.h
 * @brief Auto-generated protocol definitions — DO NOT EDIT
 *
 * Generated by ProtoEmb code generator from YAML schema
 * Protocol version: 2
 */
#ifndef PROTOEMB_H
#define PROTOEMB_H

#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* ============================================================
 * Protocol Version
 * ============================================================ */
#define PROTOEMB_PROTOCOL_VERSION 2

/* Node IDs (for multi-node / addressed framing; see build_*_frame_from). */
#define PROTOEMB_NODE_UI 0U
#define PROTOEMB_NODE_MADCORE 1U

/* ============================================================
 * Enums
 * ============================================================ */

/** Machine fault codes */
typedef enum
{
    PROTOEMB_FAULTEDREASON_NONE = 0,
    PROTOEMB_FAULTEDREASON_COG = 1,
    PROTOEMB_FAULTEDREASON_WATCHDOG = 2,
    PROTOEMB_FAULTEDREASON_ESD_POWER = 3,
    PROTOEMB_FAULTEDREASON_ESD_SWITCH = 4,
    PROTOEMB_FAULTEDREASON_ESD_UPPER = 5,
    PROTOEMB_FAULTEDREASON_ESD_LOWER = 6,
    PROTOEMB_FAULTEDREASON_SERVO_COMMUNICATION = 7,
    PROTOEMB_FAULTEDREASON_FORCE_GAUGE_COMMUNICATION = 8,
    PROTOEMB_FAULTEDREASON_COUNT = 9
} ProtoEmb_FaultedReason_E;

/** Bits needed on wire: 4 */
#define PROTOEMB_FAULTEDREASON_BITS 4


/** Motion restriction codes */
typedef enum
{
    PROTOEMB_RESTRICTEDREASON_NONE = 0,
    PROTOEMB_RESTRICTEDREASON_SAMPLE_LENGTH = 1,
    PROTOEMB_RESTRICTEDREASON_SAMPLE_TENSION = 2,
    PROTOEMB_RESTRICTEDREASON_MACHINE_TENSION = 3,
    PROTOEMB_RESTRICTEDREASON_UPPER_ENDSTOP = 4,
    PROTOEMB_RESTRICTEDREASON_LOWER_ENDSTOP = 5,
    PROTOEMB_RESTRICTEDREASON_DOOR = 6,
    PROTOEMB_RESTRICTEDREASON_COUNT = 7
} ProtoEmb_RestrictedReason_E;

/** Bits needed on wire: 3 */
#define PROTOEMB_RESTRICTEDREASON_BITS 3


/** Motion subsystem state */
typedef enum
{
    PROTOEMB_MOTIONSTATE_DISABLED = 0,
    PROTOEMB_MOTIONSTATE_WAITING = 1,
    PROTOEMB_MOTIONSTATE_MOVING = 2,
    PROTOEMB_MOTIONSTATE_COUNT = 3
} ProtoEmb_MotionState_E;

/** Bits needed on wire: 2 */
#define PROTOEMB_MOTIONSTATE_BITS 2


/** G-code command identifiers */
typedef enum
{
    PROTOEMB_GCODE_RAPID_MOVE = 0,
    PROTOEMB_GCODE_LINEAR_MOVE = 1,
    PROTOEMB_GCODE_CW_ARC = 2,
    PROTOEMB_GCODE_CCW_ARC = 3,
    PROTOEMB_GCODE_DWELL = 4,
    PROTOEMB_GCODE_HOME = 28,
    PROTOEMB_GCODE_ABSOLUTE = 90,
    PROTOEMB_GCODE_INCREMENTAL = 91,
    PROTOEMB_GCODE_STOP = 122,
    PROTOEMB_GCODE_WAVEFORM = 123,
    PROTOEMB_GCODE_COUNT = 10
} ProtoEmb_GCode_E;

/** Bits needed on wire: 4 */
#define PROTOEMB_GCODE_BITS 4

/** Remap: wire index → actual enum value */
static const uint8_t PROTOEMB_GCODE_WIRE_TO_VALUE[10] = {
    0,  /* RAPID_MOVE */
    1,  /* LINEAR_MOVE */
    2,  /* CW_ARC */
    3,  /* CCW_ARC */
    4,  /* DWELL */
    28,  /* HOME */
    90,  /* ABSOLUTE */
    91,  /* INCREMENTAL */
    122,  /* STOP */
    123  /* WAVEFORM */
};

/** Remap: actual value → wire index (sorted table + binary search, for sparse/large enums) */
typedef struct { uint8_t value; uint8_t wire; } ProtoEmb_GCode_Remap_t;
static const ProtoEmb_GCode_Remap_t PROTOEMB_GCODE_VALUE_WIRE_SORTED[10] = {
    { 0U, 0U },  /* RAPID_MOVE */
    { 1U, 1U },  /* LINEAR_MOVE */
    { 2U, 2U },  /* CW_ARC */
    { 3U, 3U },  /* CCW_ARC */
    { 4U, 4U },  /* DWELL */
    { 28U, 5U },  /* HOME */
    { 90U, 6U },  /* ABSOLUTE */
    { 91U, 7U },  /* INCREMENTAL */
    { 122U, 8U },  /* STOP */
    { 123U, 9U }  /* WAVEFORM */
};
static inline uint8_t ProtoEmb_GCode_valueToWire(uint8_t value)
{
    uint32_t lo = 0U;
    uint32_t hi = 10U;
    while (lo < hi)
    {
        const uint32_t mid = lo + ((hi - lo) / 2U);
        if (PROTOEMB_GCODE_VALUE_WIRE_SORTED[mid].value < value)
        {
            lo = mid + 1U;
        }
        else
        {
            hi = mid;
        }
    }
    if ((lo < 10U) && (PROTOEMB_GCODE_VALUE_WIRE_SORTED[lo].value == value))
    {
        return PROTOEMB_GCODE_VALUE_WIRE_SORTED[lo].wire;
    }
    return 0U;
}

/** Position-vs-time waveform function (firmware-native G123) */
typedef enum
{
    PROTOEMB_WAVEFORMSHAPE_SINE = 0,
    PROTOEMB_WAVEFORMSHAPE_TRIANGLE = 1,
    PROTOEMB_WAVEFORMSHAPE_COUNT = 2
} ProtoEmb_WaveformShape_E;

/** Bits needed on wire: 1 */
#define PROTOEMB_WAVEFORMSHAPE_BITS 1


/** Notification severity levels */
typedef enum
{
    PROTOEMB_NOTIFICATIONTYPE_MESSAGE = 0,
    PROTOEMB_NOTIFICATIONTYPE_INFO = 1,
    PROTOEMB_NOTIFICATIONTYPE_WARNING = 2,
    PROTOEMB_NOTIFICATIONTYPE_ERROR = 3,
    PROTOEMB_NOTIFICATIONTYPE_SUCCESS = 4,
    PROTOEMB_NOTIFICATIONTYPE_COUNT = 5
} ProtoEmb_NotificationType_E;

/** Bits needed on wire: 3 */
#define PROTOEMB_NOTIFICATIONTYPE_BITS 3


/** Data logging state */
typedef enum
{
    PROTOEMB_LOGGINGSTATE_IDLE = 0,
    PROTOEMB_LOGGINGSTATE_RUNNING = 1,
    PROTOEMB_LOGGINGSTATE_STOPPING = 2,
    PROTOEMB_LOGGINGSTATE_COUNT = 3
} ProtoEmb_LoggingState_E;

/** Bits needed on wire: 2 */
#define PROTOEMB_LOGGINGSTATE_BITS 2


/* ============================================================
 * Struct Wire Sizes
 * ============================================================ */
#define PROTOEMB_MACHINESTATE_WIRE_SIZE 2
#define PROTOEMB_SAMPLE_WIRE_SIZE 12
#define PROTOEMB_MOVE_WIRE_SIZE 8
#define PROTOEMB_WAVEFORMMOVE_WIRE_SIZE 9
#define PROTOEMB_STOREDSAMPLE_WIRE_SIZE 11
#define PROTOEMB_MACHINECONFIGURATION_WIRE_SIZE 68
#define PROTOEMB_SAMPLEPROFILE_WIRE_SIZE 20
#define PROTOEMB_FIRMWAREVERSION_WIRE_SIZE 16
#define PROTOEMB_TESTRUN_WIRE_SIZE 14
#define PROTOEMB_NOTIFICATION_WIRE_SIZE 101

/* ============================================================
 * Struct Types (aligned / native representation)
 * ============================================================ */

/** Machine state flags and status (packed, 2 bytes on wire) */
typedef struct
{
    ProtoEmb_FaultedReason_E faultedReason;
    ProtoEmb_RestrictedReason_E restrictedReason;
    bool testRunning;
    bool motionEnabled;
} ProtoEmb_MachineState_t;

/** Live sample data sent periodically (packed, 12 bytes on wire) */
typedef struct
{
    int32_t machineForce;
    int32_t machinePosition;
    int32_t machineSetpoint;
    int32_t sampleForce;
    int32_t samplePosition;
} ProtoEmb_Sample_t;

/** Binary motion command (G-code move) (packed, 8 bytes on wire) */
typedef struct
{
    ProtoEmb_GCode_E g;
    int32_t x;
    int32_t f;
    uint32_t p;
} ProtoEmb_Move_t;

/** Firmware-native waveform (G123): oscillate about the current position (packed, 9 bytes on wire) */
typedef struct
{
    ProtoEmb_WaveformShape_E shape;
    int32_t amplitude;
    int32_t frequency;
    uint32_t cycles;
} ProtoEmb_WaveformMove_t;

/** Sample written to SD card binary files (packed, 11 bytes on wire) */
typedef struct
{
    int32_t force;
    int32_t position;
    uint32_t time;
    int32_t setpoint;
} ProtoEmb_StoredSample_t;

/** Machine profile stored in NVRAM (aligned, 68 bytes on wire) */
typedef struct
{
    char name[20];
    int32_t encoderStepsPerMM;
    int32_t servoStepsPerMM;
    int32_t loadCellCapacity;
    int32_t loadCellSensitivity;
    int32_t loadCellZeroBalance;
    int32_t maxPosition;
    int32_t maxVelocity;
    int32_t maxAcceleration;
    int32_t maxForceTensile;
    int32_t homingVelocity;
    int32_t homingOffset;
    int32_t jawOffset;
} ProtoEmb_MachineConfiguration_t;

/** Sample profile — material test limits (aligned, 20 bytes on wire) */
typedef struct
{
    uint32_t maxForce;
    uint32_t maxVelocity;
    uint32_t maxDisplacement;
    uint32_t sampleWidth;
    uint32_t sampleThickness;
} ProtoEmb_SampleProfile_t;

/** Firmware version string (aligned, 16 bytes on wire) */
typedef struct
{
    char version[16];
} ProtoEmb_FirmwareVersion_t;

/** Test run command — references uploaded G-code and assigns test data ID (aligned, 14 bytes on wire) */
typedef struct
{
    char gcodeId[7];
    char testDataId[7];
} ProtoEmb_TestRun_t;

/** Firmware notification message (aligned, 101 bytes on wire) */
typedef struct
{
    ProtoEmb_NotificationType_E type;
    char message[100];
} ProtoEmb_Notification_t;

/* ============================================================
 * Encode / Decode Function Declarations
 * ============================================================ */

/**
 * Encode ProtoEmb_MachineState_t into 2 bytes.
 */
void ProtoEmb_MachineState_encode(uint8_t *buf, const ProtoEmb_MachineState_t *src);

/**
 * Decode 2 bytes into ProtoEmb_MachineState_t.
 */
void ProtoEmb_MachineState_decode(const uint8_t *buf, ProtoEmb_MachineState_t *dst);

/**
 * Encode ProtoEmb_Sample_t into 12 bytes.
 */
void ProtoEmb_Sample_encode(uint8_t *buf, const ProtoEmb_Sample_t *src);

/**
 * Decode 12 bytes into ProtoEmb_Sample_t.
 */
void ProtoEmb_Sample_decode(const uint8_t *buf, ProtoEmb_Sample_t *dst);

/**
 * Encode ProtoEmb_Move_t into 8 bytes.
 */
void ProtoEmb_Move_encode(uint8_t *buf, const ProtoEmb_Move_t *src);

/**
 * Decode 8 bytes into ProtoEmb_Move_t.
 */
void ProtoEmb_Move_decode(const uint8_t *buf, ProtoEmb_Move_t *dst);

/**
 * Encode ProtoEmb_WaveformMove_t into 9 bytes.
 */
void ProtoEmb_WaveformMove_encode(uint8_t *buf, const ProtoEmb_WaveformMove_t *src);

/**
 * Decode 9 bytes into ProtoEmb_WaveformMove_t.
 */
void ProtoEmb_WaveformMove_decode(const uint8_t *buf, ProtoEmb_WaveformMove_t *dst);

/**
 * Encode ProtoEmb_StoredSample_t into 11 bytes.
 */
void ProtoEmb_StoredSample_encode(uint8_t *buf, const ProtoEmb_StoredSample_t *src);

/**
 * Decode 11 bytes into ProtoEmb_StoredSample_t.
 */
void ProtoEmb_StoredSample_decode(const uint8_t *buf, ProtoEmb_StoredSample_t *dst);

/**
 * Encode ProtoEmb_MachineConfiguration_t into 68 bytes.
 */
void ProtoEmb_MachineConfiguration_encode(uint8_t *buf, const ProtoEmb_MachineConfiguration_t *src);

/**
 * Decode 68 bytes into ProtoEmb_MachineConfiguration_t.
 */
void ProtoEmb_MachineConfiguration_decode(const uint8_t *buf, ProtoEmb_MachineConfiguration_t *dst);

/**
 * Encode ProtoEmb_SampleProfile_t into 20 bytes.
 */
void ProtoEmb_SampleProfile_encode(uint8_t *buf, const ProtoEmb_SampleProfile_t *src);

/**
 * Decode 20 bytes into ProtoEmb_SampleProfile_t.
 */
void ProtoEmb_SampleProfile_decode(const uint8_t *buf, ProtoEmb_SampleProfile_t *dst);

/**
 * Encode ProtoEmb_FirmwareVersion_t into 16 bytes.
 */
void ProtoEmb_FirmwareVersion_encode(uint8_t *buf, const ProtoEmb_FirmwareVersion_t *src);

/**
 * Decode 16 bytes into ProtoEmb_FirmwareVersion_t.
 */
void ProtoEmb_FirmwareVersion_decode(const uint8_t *buf, ProtoEmb_FirmwareVersion_t *dst);

/**
 * Encode ProtoEmb_TestRun_t into 14 bytes.
 */
void ProtoEmb_TestRun_encode(uint8_t *buf, const ProtoEmb_TestRun_t *src);

/**
 * Decode 14 bytes into ProtoEmb_TestRun_t.
 */
void ProtoEmb_TestRun_decode(const uint8_t *buf, ProtoEmb_TestRun_t *dst);

/**
 * Encode ProtoEmb_Notification_t into 101 bytes.
 */
void ProtoEmb_Notification_encode(uint8_t *buf, const ProtoEmb_Notification_t *src);

/**
 * Decode 101 bytes into ProtoEmb_Notification_t.
 */
void ProtoEmb_Notification_decode(const uint8_t *buf, ProtoEmb_Notification_t *dst);

/* ============================================================
 * Scaled Field Accessors (raw_storage fields)
 *
 * For fields with raw_storage: true, the struct holds the
 * scaled integer directly (e.g. mN, µm).  Use these helpers:
 *   _set<Field>(s, float)   — physical units → scaled integer
 *   _set<Field>_raw(s, int) — assign scaled integer directly
 *   _get<Field>(s)          — scaled integer → physical units (float)
 *   _get<Field>_raw(s)      — read scaled integer directly
 * ============================================================ */

/** Set Sample.machineForce from physical N (scale × 1000 → stored as int). */
static inline void ProtoEmb_Sample_setMachineForce(ProtoEmb_Sample_t *s, float val)
{
    s->machineForce = (int32_t)(val * 1000.0f);
}

/** Set Sample.machineForce directly as raw scaled integer (N × 1000). */
static inline void ProtoEmb_Sample_setMachineForce_raw(ProtoEmb_Sample_t *s, int32_t raw)
{
    s->machineForce = raw;
}

/** Get Sample.machineForce as physical N (divides stored int by 1000). */
static inline float ProtoEmb_Sample_getMachineForce(const ProtoEmb_Sample_t *s)
{
    return (float)s->machineForce / 1000.0f;
}

/** Get Sample.machineForce as raw scaled integer (N × 1000). */
static inline int32_t ProtoEmb_Sample_getMachineForce_raw(const ProtoEmb_Sample_t *s)
{
    return s->machineForce;
}

/** Set Sample.machinePosition from physical mm (scale × 1000 → stored as int). */
static inline void ProtoEmb_Sample_setMachinePosition(ProtoEmb_Sample_t *s, float val)
{
    s->machinePosition = (int32_t)(val * 1000.0f);
}

/** Set Sample.machinePosition directly as raw scaled integer (mm × 1000). */
static inline void ProtoEmb_Sample_setMachinePosition_raw(ProtoEmb_Sample_t *s, int32_t raw)
{
    s->machinePosition = raw;
}

/** Get Sample.machinePosition as physical mm (divides stored int by 1000). */
static inline float ProtoEmb_Sample_getMachinePosition(const ProtoEmb_Sample_t *s)
{
    return (float)s->machinePosition / 1000.0f;
}

/** Get Sample.machinePosition as raw scaled integer (mm × 1000). */
static inline int32_t ProtoEmb_Sample_getMachinePosition_raw(const ProtoEmb_Sample_t *s)
{
    return s->machinePosition;
}

/** Set Sample.machineSetpoint from physical mm (scale × 1000 → stored as int). */
static inline void ProtoEmb_Sample_setMachineSetpoint(ProtoEmb_Sample_t *s, float val)
{
    s->machineSetpoint = (int32_t)(val * 1000.0f);
}

/** Set Sample.machineSetpoint directly as raw scaled integer (mm × 1000). */
static inline void ProtoEmb_Sample_setMachineSetpoint_raw(ProtoEmb_Sample_t *s, int32_t raw)
{
    s->machineSetpoint = raw;
}

/** Get Sample.machineSetpoint as physical mm (divides stored int by 1000). */
static inline float ProtoEmb_Sample_getMachineSetpoint(const ProtoEmb_Sample_t *s)
{
    return (float)s->machineSetpoint / 1000.0f;
}

/** Get Sample.machineSetpoint as raw scaled integer (mm × 1000). */
static inline int32_t ProtoEmb_Sample_getMachineSetpoint_raw(const ProtoEmb_Sample_t *s)
{
    return s->machineSetpoint;
}

/** Set Sample.sampleForce from physical N (scale × 1000 → stored as int). */
static inline void ProtoEmb_Sample_setSampleForce(ProtoEmb_Sample_t *s, float val)
{
    s->sampleForce = (int32_t)(val * 1000.0f);
}

/** Set Sample.sampleForce directly as raw scaled integer (N × 1000). */
static inline void ProtoEmb_Sample_setSampleForce_raw(ProtoEmb_Sample_t *s, int32_t raw)
{
    s->sampleForce = raw;
}

/** Get Sample.sampleForce as physical N (divides stored int by 1000). */
static inline float ProtoEmb_Sample_getSampleForce(const ProtoEmb_Sample_t *s)
{
    return (float)s->sampleForce / 1000.0f;
}

/** Get Sample.sampleForce as raw scaled integer (N × 1000). */
static inline int32_t ProtoEmb_Sample_getSampleForce_raw(const ProtoEmb_Sample_t *s)
{
    return s->sampleForce;
}

/** Set Sample.samplePosition from physical mm (scale × 1000 → stored as int). */
static inline void ProtoEmb_Sample_setSamplePosition(ProtoEmb_Sample_t *s, float val)
{
    s->samplePosition = (int32_t)(val * 1000.0f);
}

/** Set Sample.samplePosition directly as raw scaled integer (mm × 1000). */
static inline void ProtoEmb_Sample_setSamplePosition_raw(ProtoEmb_Sample_t *s, int32_t raw)
{
    s->samplePosition = raw;
}

/** Get Sample.samplePosition as physical mm (divides stored int by 1000). */
static inline float ProtoEmb_Sample_getSamplePosition(const ProtoEmb_Sample_t *s)
{
    return (float)s->samplePosition / 1000.0f;
}

/** Get Sample.samplePosition as raw scaled integer (mm × 1000). */
static inline int32_t ProtoEmb_Sample_getSamplePosition_raw(const ProtoEmb_Sample_t *s)
{
    return s->samplePosition;
}

/** Set Move.x from physical mm (scale × 1000 → stored as int). */
static inline void ProtoEmb_Move_setX(ProtoEmb_Move_t *s, float val)
{
    s->x = (int32_t)(val * 1000.0f);
}

/** Set Move.x directly as raw scaled integer (mm × 1000). */
static inline void ProtoEmb_Move_setX_raw(ProtoEmb_Move_t *s, int32_t raw)
{
    s->x = raw;
}

/** Get Move.x as physical mm (divides stored int by 1000). */
static inline float ProtoEmb_Move_getX(const ProtoEmb_Move_t *s)
{
    return (float)s->x / 1000.0f;
}

/** Get Move.x as raw scaled integer (mm × 1000). */
static inline int32_t ProtoEmb_Move_getX_raw(const ProtoEmb_Move_t *s)
{
    return s->x;
}

/** Set Move.f from physical mm/s (scale × 1000 → stored as int). */
static inline void ProtoEmb_Move_setF(ProtoEmb_Move_t *s, float val)
{
    s->f = (int32_t)(val * 1000.0f);
}

/** Set Move.f directly as raw scaled integer (mm/s × 1000). */
static inline void ProtoEmb_Move_setF_raw(ProtoEmb_Move_t *s, int32_t raw)
{
    s->f = raw;
}

/** Get Move.f as physical mm/s (divides stored int by 1000). */
static inline float ProtoEmb_Move_getF(const ProtoEmb_Move_t *s)
{
    return (float)s->f / 1000.0f;
}

/** Get Move.f as raw scaled integer (mm/s × 1000). */
static inline int32_t ProtoEmb_Move_getF_raw(const ProtoEmb_Move_t *s)
{
    return s->f;
}

/** Set WaveformMove.amplitude from physical mm (scale × 1000 → stored as int). */
static inline void ProtoEmb_WaveformMove_setAmplitude(ProtoEmb_WaveformMove_t *s, float val)
{
    s->amplitude = (int32_t)(val * 1000.0f);
}

/** Set WaveformMove.amplitude directly as raw scaled integer (mm × 1000). */
static inline void ProtoEmb_WaveformMove_setAmplitude_raw(ProtoEmb_WaveformMove_t *s, int32_t raw)
{
    s->amplitude = raw;
}

/** Get WaveformMove.amplitude as physical mm (divides stored int by 1000). */
static inline float ProtoEmb_WaveformMove_getAmplitude(const ProtoEmb_WaveformMove_t *s)
{
    return (float)s->amplitude / 1000.0f;
}

/** Get WaveformMove.amplitude as raw scaled integer (mm × 1000). */
static inline int32_t ProtoEmb_WaveformMove_getAmplitude_raw(const ProtoEmb_WaveformMove_t *s)
{
    return s->amplitude;
}

/** Set WaveformMove.frequency from physical Hz (scale × 1000 → stored as int). */
static inline void ProtoEmb_WaveformMove_setFrequency(ProtoEmb_WaveformMove_t *s, float val)
{
    s->frequency = (int32_t)(val * 1000.0f);
}

/** Set WaveformMove.frequency directly as raw scaled integer (Hz × 1000). */
static inline void ProtoEmb_WaveformMove_setFrequency_raw(ProtoEmb_WaveformMove_t *s, int32_t raw)
{
    s->frequency = raw;
}

/** Get WaveformMove.frequency as physical Hz (divides stored int by 1000). */
static inline float ProtoEmb_WaveformMove_getFrequency(const ProtoEmb_WaveformMove_t *s)
{
    return (float)s->frequency / 1000.0f;
}

/** Get WaveformMove.frequency as raw scaled integer (Hz × 1000). */
static inline int32_t ProtoEmb_WaveformMove_getFrequency_raw(const ProtoEmb_WaveformMove_t *s)
{
    return s->frequency;
}

/** Set StoredSample.force from physical N (scale × 1000 → stored as int). */
static inline void ProtoEmb_StoredSample_setForce(ProtoEmb_StoredSample_t *s, float val)
{
    s->force = (int32_t)(val * 1000.0f);
}

/** Set StoredSample.force directly as raw scaled integer (N × 1000). */
static inline void ProtoEmb_StoredSample_setForce_raw(ProtoEmb_StoredSample_t *s, int32_t raw)
{
    s->force = raw;
}

/** Get StoredSample.force as physical N (divides stored int by 1000). */
static inline float ProtoEmb_StoredSample_getForce(const ProtoEmb_StoredSample_t *s)
{
    return (float)s->force / 1000.0f;
}

/** Get StoredSample.force as raw scaled integer (N × 1000). */
static inline int32_t ProtoEmb_StoredSample_getForce_raw(const ProtoEmb_StoredSample_t *s)
{
    return s->force;
}

/** Set StoredSample.position from physical mm (scale × 1000 → stored as int). */
static inline void ProtoEmb_StoredSample_setPosition(ProtoEmb_StoredSample_t *s, float val)
{
    s->position = (int32_t)(val * 1000.0f);
}

/** Set StoredSample.position directly as raw scaled integer (mm × 1000). */
static inline void ProtoEmb_StoredSample_setPosition_raw(ProtoEmb_StoredSample_t *s, int32_t raw)
{
    s->position = raw;
}

/** Get StoredSample.position as physical mm (divides stored int by 1000). */
static inline float ProtoEmb_StoredSample_getPosition(const ProtoEmb_StoredSample_t *s)
{
    return (float)s->position / 1000.0f;
}

/** Get StoredSample.position as raw scaled integer (mm × 1000). */
static inline int32_t ProtoEmb_StoredSample_getPosition_raw(const ProtoEmb_StoredSample_t *s)
{
    return s->position;
}

/** Set StoredSample.setpoint from physical mm (scale × 1000 → stored as int). */
static inline void ProtoEmb_StoredSample_setSetpoint(ProtoEmb_StoredSample_t *s, float val)
{
    s->setpoint = (int32_t)(val * 1000.0f);
}

/** Set StoredSample.setpoint directly as raw scaled integer (mm × 1000). */
static inline void ProtoEmb_StoredSample_setSetpoint_raw(ProtoEmb_StoredSample_t *s, int32_t raw)
{
    s->setpoint = raw;
}

/** Get StoredSample.setpoint as physical mm (divides stored int by 1000). */
static inline float ProtoEmb_StoredSample_getSetpoint(const ProtoEmb_StoredSample_t *s)
{
    return (float)s->setpoint / 1000.0f;
}

/** Get StoredSample.setpoint as raw scaled integer (mm × 1000). */
static inline int32_t ProtoEmb_StoredSample_getSetpoint_raw(const ProtoEmb_StoredSample_t *s)
{
    return s->setpoint;
}

/** Set MachineConfiguration.loadCellCapacity from physical N (scale × 1000 → stored as int). */
static inline void ProtoEmb_MachineConfiguration_setLoadCellCapacity(ProtoEmb_MachineConfiguration_t *s, float val)
{
    s->loadCellCapacity = (int32_t)(val * 1000.0f);
}

/** Set MachineConfiguration.loadCellCapacity directly as raw scaled integer (N × 1000). */
static inline void ProtoEmb_MachineConfiguration_setLoadCellCapacity_raw(ProtoEmb_MachineConfiguration_t *s, int32_t raw)
{
    s->loadCellCapacity = raw;
}

/** Get MachineConfiguration.loadCellCapacity as physical N (divides stored int by 1000). */
static inline float ProtoEmb_MachineConfiguration_getLoadCellCapacity(const ProtoEmb_MachineConfiguration_t *s)
{
    return (float)s->loadCellCapacity / 1000.0f;
}

/** Get MachineConfiguration.loadCellCapacity as raw scaled integer (N × 1000). */
static inline int32_t ProtoEmb_MachineConfiguration_getLoadCellCapacity_raw(const ProtoEmb_MachineConfiguration_t *s)
{
    return s->loadCellCapacity;
}

/** Set MachineConfiguration.maxForceTensile from physical N (scale × 1000 → stored as int). */
static inline void ProtoEmb_MachineConfiguration_setMaxForceTensile(ProtoEmb_MachineConfiguration_t *s, float val)
{
    s->maxForceTensile = (int32_t)(val * 1000.0f);
}

/** Set MachineConfiguration.maxForceTensile directly as raw scaled integer (N × 1000). */
static inline void ProtoEmb_MachineConfiguration_setMaxForceTensile_raw(ProtoEmb_MachineConfiguration_t *s, int32_t raw)
{
    s->maxForceTensile = raw;
}

/** Get MachineConfiguration.maxForceTensile as physical N (divides stored int by 1000). */
static inline float ProtoEmb_MachineConfiguration_getMaxForceTensile(const ProtoEmb_MachineConfiguration_t *s)
{
    return (float)s->maxForceTensile / 1000.0f;
}

/** Get MachineConfiguration.maxForceTensile as raw scaled integer (N × 1000). */
static inline int32_t ProtoEmb_MachineConfiguration_getMaxForceTensile_raw(const ProtoEmb_MachineConfiguration_t *s)
{
    return s->maxForceTensile;
}

/** Set SampleProfile.maxForce from physical N (scale × 1000 → stored as int). */
static inline void ProtoEmb_SampleProfile_setMaxForce(ProtoEmb_SampleProfile_t *s, float val)
{
    s->maxForce = (int32_t)(val * 1000.0f);
}

/** Set SampleProfile.maxForce directly as raw scaled integer (N × 1000). */
static inline void ProtoEmb_SampleProfile_setMaxForce_raw(ProtoEmb_SampleProfile_t *s, int32_t raw)
{
    s->maxForce = raw;
}

/** Get SampleProfile.maxForce as physical N (divides stored int by 1000). */
static inline float ProtoEmb_SampleProfile_getMaxForce(const ProtoEmb_SampleProfile_t *s)
{
    return (float)s->maxForce / 1000.0f;
}

/** Get SampleProfile.maxForce as raw scaled integer (N × 1000). */
static inline int32_t ProtoEmb_SampleProfile_getMaxForce_raw(const ProtoEmb_SampleProfile_t *s)
{
    return s->maxForce;
}

/* ============================================================
 * Message Command IDs
 * ============================================================ */
#define PROTOEMB_MSG_READ_SAMPLE 0
#define PROTOEMB_MSG_READ_STATE 1
#define PROTOEMB_MSG_READ_MACHINE_CONFIGURATION 2
#define PROTOEMB_MSG_READ_FIRMWARE_VERSION 3
#define PROTOEMB_MSG_READ_SAMPLE_PROFILE 4
#define PROTOEMB_MSG_WRITE_MACHINE_CONFIGURATION_WRITE 0
#define PROTOEMB_MSG_WRITE_MOTION_ENABLE 1
#define PROTOEMB_MSG_WRITE_TEST_RUN 2
#define PROTOEMB_MSG_WRITE_MANUAL_MOVE 3
#define PROTOEMB_MSG_WRITE_TEST_MOVE 4
#define PROTOEMB_MSG_WRITE_TEST_WAVEFORM 8
#define PROTOEMB_MSG_WRITE_SAMPLE_PROFILE_WRITE 5
#define PROTOEMB_MSG_WRITE_GAUGE_LENGTH 6
#define PROTOEMB_MSG_WRITE_GAUGE_FORCE 7
#define PROTOEMB_MSG_WRITE_FILE_DOWNLOAD 9

/* ============================================================
 * Periodic Message Periods (ms)
 * ============================================================ */
#define PROTOEMB_MSG_SAMPLE_PERIOD_MS 10
#define PROTOEMB_MSG_STATE_PERIOD_MS 1000

#endif /* PROTOEMB_H */
