/**
 * @file protoemb.c
 * @brief Auto-generated protocol encode/decode — DO NOT EDIT
 *
 * Generated by ProtoEmb code generator from YAML schema
 * Protocol version: 2
 */

#include "protoemb.h"

/* ============================================================
 * Packed Encode / Decode Helpers
 * ============================================================ */

/** Write `bits` bits from `value` into buf starting at bit offset `bit_off`. LSB-first. */
static void pack_bits(uint8_t *buf, uint32_t bit_off, uint32_t bits, uint32_t value)
{
    for (uint32_t i = 0; i < bits; i++)
    {
        const uint32_t byte_idx = (bit_off + i) / 8;
        const uint32_t bit_idx = (bit_off + i) % 8;
        if ((value >> i) & 1U)
        {
            buf[byte_idx] |= (1U << bit_idx);
        }
    }
}

/** Read `bits` bits from buf starting at bit offset `bit_off`. LSB-first. Returns unsigned. */
static uint32_t unpack_bits(const uint8_t *buf, uint32_t bit_off, uint32_t bits)
{
    uint32_t value = 0;
    for (uint32_t i = 0; i < bits; i++)
    {
        const uint32_t byte_idx = (bit_off + i) / 8;
        const uint32_t bit_idx = (bit_off + i) % 8;
        if ((buf[byte_idx] >> bit_idx) & 1U)
        {
            value |= (1U << i);
        }
    }
    return value;
}

/** Sign-extend a value from `bits` width to int32_t */
static int32_t sign_extend(uint32_t value, uint32_t bits)
{
    if (bits >= 32)
    {
        return (int32_t)value;
    }
    const uint32_t sign_bit = 1U << (bits - 1);
    if (value & sign_bit)
    {
        /* Set all upper bits */
        value |= ~((1U << bits) - 1);
    }
    return (int32_t)value;
}

/* ============================================================
 * Struct Encode / Decode Implementations
 * ============================================================ */

/* ── MachineState (packed, 2 bytes) ── */

void ProtoEmb_MachineState_encode(uint8_t *buf, const ProtoEmb_MachineState_t *src)
{
    memset(buf, 0, PROTOEMB_MACHINESTATE_WIRE_SIZE);
    pack_bits(buf, 0, 4, (uint32_t)src->faultedReason);
    pack_bits(buf, 4, 3, (uint32_t)src->restrictedReason);
    pack_bits(buf, 7, 1, src->testRunning ? 1U : 0U);
    pack_bits(buf, 8, 1, src->motionEnabled ? 1U : 0U);
}

void ProtoEmb_MachineState_decode(const uint8_t *buf, ProtoEmb_MachineState_t *dst)
{
    memset(dst, 0, sizeof(ProtoEmb_MachineState_t));
    dst->faultedReason = (ProtoEmb_FaultedReason_E)unpack_bits(buf, 0, 4);
    dst->restrictedReason = (ProtoEmb_RestrictedReason_E)unpack_bits(buf, 4, 3);
    dst->testRunning = unpack_bits(buf, 7, 1) != 0;
    dst->motionEnabled = unpack_bits(buf, 8, 1) != 0;
}

/* ── Sample (packed, 12 bytes) ── */

void ProtoEmb_Sample_encode(uint8_t *buf, const ProtoEmb_Sample_t *src)
{
    memset(buf, 0, PROTOEMB_SAMPLE_WIRE_SIZE);
    /* Raw storage: struct holds scaled integer, just subtract wire offset */
    pack_bits(buf, 0, 18, (uint32_t)(src->machineForce - (-100000)));
    /* Raw storage: struct holds scaled integer, just subtract wire offset */
    pack_bits(buf, 18, 19, (uint32_t)(src->machinePosition - (-200000)));
    /* Raw storage: struct holds scaled integer, just subtract wire offset */
    pack_bits(buf, 37, 19, (uint32_t)(src->machineSetpoint - (-200000)));
    /* Raw storage: struct holds scaled integer, just subtract wire offset */
    pack_bits(buf, 56, 18, (uint32_t)(src->sampleForce - (-100000)));
    /* Raw storage: struct holds scaled integer, just subtract wire offset */
    pack_bits(buf, 74, 19, (uint32_t)(src->samplePosition - (-200000)));
}

void ProtoEmb_Sample_decode(const uint8_t *buf, ProtoEmb_Sample_t *dst)
{
    memset(dst, 0, sizeof(ProtoEmb_Sample_t));
    /* Raw storage: decode to scaled integer, no scale division */
    dst->machineForce = (int32_t)unpack_bits(buf, 0, 18) + (-100000);
    /* Raw storage: decode to scaled integer, no scale division */
    dst->machinePosition = (int32_t)unpack_bits(buf, 18, 19) + (-200000);
    /* Raw storage: decode to scaled integer, no scale division */
    dst->machineSetpoint = (int32_t)unpack_bits(buf, 37, 19) + (-200000);
    /* Raw storage: decode to scaled integer, no scale division */
    dst->sampleForce = (int32_t)unpack_bits(buf, 56, 18) + (-100000);
    /* Raw storage: decode to scaled integer, no scale division */
    dst->samplePosition = (int32_t)unpack_bits(buf, 74, 19) + (-200000);
}

/* ── Move (packed, 8 bytes) ── */

void ProtoEmb_Move_encode(uint8_t *buf, const ProtoEmb_Move_t *src)
{
    memset(buf, 0, PROTOEMB_MOVE_WIRE_SIZE);
    pack_bits(buf, 0, 4, ProtoEmb_GCode_valueToWire((uint8_t)src->g));
    /* Raw storage: struct holds scaled integer, just subtract wire offset */
    pack_bits(buf, 4, 22, (uint32_t)(src->x - (-200000)));
    /* Raw storage: struct holds scaled integer, just subtract wire offset */
    pack_bits(buf, 26, 22, (uint32_t)(src->f - (0)));
    pack_bits(buf, 48, 16, (uint32_t)(src->p * 1));
}

void ProtoEmb_Move_decode(const uint8_t *buf, ProtoEmb_Move_t *dst)
{
    memset(dst, 0, sizeof(ProtoEmb_Move_t));
    {
        const uint32_t wire_idx = unpack_bits(buf, 0, 4);
        dst->g = (ProtoEmb_GCode_E)PROTOEMB_GCODE_WIRE_TO_VALUE[wire_idx];
    }
    /* Raw storage: decode to scaled integer, no scale division */
    dst->x = (int32_t)unpack_bits(buf, 4, 22) + (-200000);
    /* Raw storage: decode to scaled integer, no scale division */
    dst->f = (int32_t)unpack_bits(buf, 26, 22) + (0);
    dst->p = unpack_bits(buf, 48, 16) / 1;
}

/* ── WaveformMove (packed, 9 bytes) ── */

void ProtoEmb_WaveformMove_encode(uint8_t *buf, const ProtoEmb_WaveformMove_t *src)
{
    memset(buf, 0, PROTOEMB_WAVEFORMMOVE_WIRE_SIZE);
    pack_bits(buf, 0, 1, (uint32_t)src->shape);
    /* Raw storage: struct holds scaled integer, just subtract wire offset */
    pack_bits(buf, 1, 22, (uint32_t)(src->amplitude - (0)));
    /* Raw storage: struct holds scaled integer, just subtract wire offset */
    pack_bits(buf, 23, 20, (uint32_t)(src->frequency - (0)));
    pack_bits(buf, 43, 24, (uint32_t)((src->cycles - (1)) * 1));
}

void ProtoEmb_WaveformMove_decode(const uint8_t *buf, ProtoEmb_WaveformMove_t *dst)
{
    memset(dst, 0, sizeof(ProtoEmb_WaveformMove_t));
    dst->shape = (ProtoEmb_WaveformShape_E)unpack_bits(buf, 0, 1);
    /* Raw storage: decode to scaled integer, no scale division */
    dst->amplitude = (int32_t)unpack_bits(buf, 1, 22) + (0);
    /* Raw storage: decode to scaled integer, no scale division */
    dst->frequency = (int32_t)unpack_bits(buf, 23, 20) + (0);
    dst->cycles = unpack_bits(buf, 43, 24) / 1 + (1);
}

/* ── StoredSample (packed, 11 bytes) ── */

void ProtoEmb_StoredSample_encode(uint8_t *buf, const ProtoEmb_StoredSample_t *src)
{
    memset(buf, 0, PROTOEMB_STOREDSAMPLE_WIRE_SIZE);
    /* Raw storage: struct holds scaled integer, just subtract wire offset */
    pack_bits(buf, 0, 18, (uint32_t)(src->force - (-100000)));
    /* Raw storage: struct holds scaled integer, just subtract wire offset */
    pack_bits(buf, 18, 19, (uint32_t)(src->position - (-200000)));
    pack_bits(buf, 37, 32, (uint32_t)(src->time * 1));
    /* Raw storage: struct holds scaled integer, just subtract wire offset */
    pack_bits(buf, 69, 19, (uint32_t)(src->setpoint - (-200000)));
}

void ProtoEmb_StoredSample_decode(const uint8_t *buf, ProtoEmb_StoredSample_t *dst)
{
    memset(dst, 0, sizeof(ProtoEmb_StoredSample_t));
    /* Raw storage: decode to scaled integer, no scale division */
    dst->force = (int32_t)unpack_bits(buf, 0, 18) + (-100000);
    /* Raw storage: decode to scaled integer, no scale division */
    dst->position = (int32_t)unpack_bits(buf, 18, 19) + (-200000);
    dst->time = unpack_bits(buf, 37, 32) / 1;
    /* Raw storage: decode to scaled integer, no scale division */
    dst->setpoint = (int32_t)unpack_bits(buf, 69, 19) + (-200000);
}

/* ── MachineConfiguration (aligned, 68 bytes) ── */

void ProtoEmb_MachineConfiguration_encode(uint8_t *buf, const ProtoEmb_MachineConfiguration_t *src)
{
    memset(buf, 0, PROTOEMB_MACHINECONFIGURATION_WIRE_SIZE);
    /* Aligned encoding — sequential memcpy */
    uint32_t offset = 0;
    memcpy(&buf[offset], src->name, 20);
    offset += 20;
    memcpy(&buf[offset], &src->encoderStepsPerMM, 4);
    offset += 4;
    memcpy(&buf[offset], &src->servoStepsPerMM, 4);
    offset += 4;
    memcpy(&buf[offset], &src->loadCellCapacity, 4);
    offset += 4;
    memcpy(&buf[offset], &src->loadCellSensitivity, 4);
    offset += 4;
    memcpy(&buf[offset], &src->loadCellZeroBalance, 4);
    offset += 4;
    memcpy(&buf[offset], &src->maxPosition, 4);
    offset += 4;
    memcpy(&buf[offset], &src->maxVelocity, 4);
    offset += 4;
    memcpy(&buf[offset], &src->maxAcceleration, 4);
    offset += 4;
    memcpy(&buf[offset], &src->maxForceTensile, 4);
    offset += 4;
    memcpy(&buf[offset], &src->homingVelocity, 4);
    offset += 4;
    memcpy(&buf[offset], &src->homingOffset, 4);
    offset += 4;
    memcpy(&buf[offset], &src->jawOffset, 4);
    offset += 4;
    (void)offset; /* suppress unused warning */
}

void ProtoEmb_MachineConfiguration_decode(const uint8_t *buf, ProtoEmb_MachineConfiguration_t *dst)
{
    memset(dst, 0, sizeof(ProtoEmb_MachineConfiguration_t));
    /* Aligned decoding — sequential memcpy */
    uint32_t offset = 0;
    memcpy(dst->name, &buf[offset], 20);
    offset += 20;
    memcpy(&dst->encoderStepsPerMM, &buf[offset], 4);
    offset += 4;
    memcpy(&dst->servoStepsPerMM, &buf[offset], 4);
    offset += 4;
    memcpy(&dst->loadCellCapacity, &buf[offset], 4);
    offset += 4;
    memcpy(&dst->loadCellSensitivity, &buf[offset], 4);
    offset += 4;
    memcpy(&dst->loadCellZeroBalance, &buf[offset], 4);
    offset += 4;
    memcpy(&dst->maxPosition, &buf[offset], 4);
    offset += 4;
    memcpy(&dst->maxVelocity, &buf[offset], 4);
    offset += 4;
    memcpy(&dst->maxAcceleration, &buf[offset], 4);
    offset += 4;
    memcpy(&dst->maxForceTensile, &buf[offset], 4);
    offset += 4;
    memcpy(&dst->homingVelocity, &buf[offset], 4);
    offset += 4;
    memcpy(&dst->homingOffset, &buf[offset], 4);
    offset += 4;
    memcpy(&dst->jawOffset, &buf[offset], 4);
    offset += 4;
    (void)offset;
}

/* ── SampleProfile (aligned, 20 bytes) ── */

void ProtoEmb_SampleProfile_encode(uint8_t *buf, const ProtoEmb_SampleProfile_t *src)
{
    memset(buf, 0, PROTOEMB_SAMPLEPROFILE_WIRE_SIZE);
    /* Aligned encoding — sequential memcpy */
    uint32_t offset = 0;
    memcpy(&buf[offset], &src->maxForce, 4);
    offset += 4;
    memcpy(&buf[offset], &src->maxVelocity, 4);
    offset += 4;
    memcpy(&buf[offset], &src->maxDisplacement, 4);
    offset += 4;
    memcpy(&buf[offset], &src->sampleWidth, 4);
    offset += 4;
    memcpy(&buf[offset], &src->sampleThickness, 4);
    offset += 4;
    (void)offset; /* suppress unused warning */
}

void ProtoEmb_SampleProfile_decode(const uint8_t *buf, ProtoEmb_SampleProfile_t *dst)
{
    memset(dst, 0, sizeof(ProtoEmb_SampleProfile_t));
    /* Aligned decoding — sequential memcpy */
    uint32_t offset = 0;
    memcpy(&dst->maxForce, &buf[offset], 4);
    offset += 4;
    memcpy(&dst->maxVelocity, &buf[offset], 4);
    offset += 4;
    memcpy(&dst->maxDisplacement, &buf[offset], 4);
    offset += 4;
    memcpy(&dst->sampleWidth, &buf[offset], 4);
    offset += 4;
    memcpy(&dst->sampleThickness, &buf[offset], 4);
    offset += 4;
    (void)offset;
}

/* ── FirmwareVersion (aligned, 16 bytes) ── */

void ProtoEmb_FirmwareVersion_encode(uint8_t *buf, const ProtoEmb_FirmwareVersion_t *src)
{
    memset(buf, 0, PROTOEMB_FIRMWAREVERSION_WIRE_SIZE);
    /* Aligned encoding — sequential memcpy */
    uint32_t offset = 0;
    memcpy(&buf[offset], src->version, 16);
    offset += 16;
    (void)offset; /* suppress unused warning */
}

void ProtoEmb_FirmwareVersion_decode(const uint8_t *buf, ProtoEmb_FirmwareVersion_t *dst)
{
    memset(dst, 0, sizeof(ProtoEmb_FirmwareVersion_t));
    /* Aligned decoding — sequential memcpy */
    uint32_t offset = 0;
    memcpy(dst->version, &buf[offset], 16);
    offset += 16;
    (void)offset;
}

/* ── TestRun (aligned, 14 bytes) ── */

void ProtoEmb_TestRun_encode(uint8_t *buf, const ProtoEmb_TestRun_t *src)
{
    memset(buf, 0, PROTOEMB_TESTRUN_WIRE_SIZE);
    /* Aligned encoding — sequential memcpy */
    uint32_t offset = 0;
    memcpy(&buf[offset], src->gcodeId, 7);
    offset += 7;
    memcpy(&buf[offset], src->testDataId, 7);
    offset += 7;
    (void)offset; /* suppress unused warning */
}

void ProtoEmb_TestRun_decode(const uint8_t *buf, ProtoEmb_TestRun_t *dst)
{
    memset(dst, 0, sizeof(ProtoEmb_TestRun_t));
    /* Aligned decoding — sequential memcpy */
    uint32_t offset = 0;
    memcpy(dst->gcodeId, &buf[offset], 7);
    offset += 7;
    memcpy(dst->testDataId, &buf[offset], 7);
    offset += 7;
    (void)offset;
}

/* ── Notification (aligned, 101 bytes) ── */

void ProtoEmb_Notification_encode(uint8_t *buf, const ProtoEmb_Notification_t *src)
{
    memset(buf, 0, PROTOEMB_NOTIFICATION_WIRE_SIZE);
    /* Aligned encoding — sequential memcpy */
    uint32_t offset = 0;
    buf[offset] = (uint8_t)src->type;
    offset += 1;
    memcpy(&buf[offset], src->message, 100);
    offset += 100;
    (void)offset; /* suppress unused warning */
}

void ProtoEmb_Notification_decode(const uint8_t *buf, ProtoEmb_Notification_t *dst)
{
    memset(dst, 0, sizeof(ProtoEmb_Notification_t));
    /* Aligned decoding — sequential memcpy */
    uint32_t offset = 0;
    dst->type = (ProtoEmb_NotificationType_E)buf[offset];
    offset += 1;
    memcpy(dst->message, &buf[offset], 100);
    offset += 100;
    (void)offset;
}
