/**
 * protoemb.ts
 * Auto-generated protocol definitions — DO NOT EDIT
 *
 * Generated by ProtoEmb code generator from YAML schema
 * Protocol version: 2
 */

/* eslint-disable no-bitwise */

export const PROTOCOL_VERSION = 2;

/** Node IDs (for multi-node / addressed framing). */
export const NODE = {
    UI: 0,
    MADCORE: 1,
} as const;

/* ── Per-element leaf macros (used for array elements; off/val are expressions) ── */

// ============================================================
// Enums
// ============================================================

/** Machine fault codes */
export enum FaultedReason {
    NONE = 0,
    COG = 1,
    WATCHDOG = 2,
    ESD_POWER = 3,
    ESD_SWITCH = 4,
    ESD_UPPER = 5,
    ESD_LOWER = 6,
    SERVO_COMMUNICATION = 7,
    FORCE_GAUGE_COMMUNICATION = 8,
}

/** Motion restriction codes */
export enum RestrictedReason {
    NONE = 0,
    SAMPLE_LENGTH = 1,
    SAMPLE_TENSION = 2,
    MACHINE_TENSION = 3,
    UPPER_ENDSTOP = 4,
    LOWER_ENDSTOP = 5,
    DOOR = 6,
}

/** Motion subsystem state */
export enum MotionState {
    DISABLED = 0,
    WAITING = 1,
    MOVING = 2,
}

/** G-code command identifiers */
export enum GCode {
    RAPID_MOVE = 0,
    LINEAR_MOVE = 1,
    CW_ARC = 2,
    CCW_ARC = 3,
    DWELL = 4,
    HOME = 28,
    ABSOLUTE = 90,
    INCREMENTAL = 91,
    STOP = 122,
    WAVEFORM = 123,
}

/** Remap: wire index → actual value */
export const GCODE_WIRE_TO_VALUE: number[] = [
    0,  // RAPID_MOVE
    1,  // LINEAR_MOVE
    2,  // CW_ARC
    3,  // CCW_ARC
    4,  // DWELL
    28,  // HOME
    90,  // ABSOLUTE
    91,  // INCREMENTAL
    122,  // STOP
    123,  // WAVEFORM
];

/** Remap: actual value → wire index */
export const GCODE_VALUE_TO_WIRE: Record<number, number> = {
    0: 0,  // RAPID_MOVE
    1: 1,  // LINEAR_MOVE
    2: 2,  // CW_ARC
    3: 3,  // CCW_ARC
    4: 4,  // DWELL
    28: 5,  // HOME
    90: 6,  // ABSOLUTE
    91: 7,  // INCREMENTAL
    122: 8,  // STOP
    123: 9,  // WAVEFORM
};

/** Position-vs-time waveform function (firmware-native G123) */
export enum WaveformShape {
    SINE = 0,
    TRIANGLE = 1,
}

/** Notification severity levels */
export enum NotificationType {
    MESSAGE = 0,
    INFO = 1,
    WARNING = 2,
    ERROR = 3,
    SUCCESS = 4,
}

/** Data logging state */
export enum LoggingState {
    IDLE = 0,
    RUNNING = 1,
    STOPPING = 2,
}


// ============================================================
// Struct Interfaces (application units)
// ============================================================

/** Machine state flags and status — 2 bytes on wire */
export interface MachineState {
    faultedReason: FaultedReason;
    restrictedReason: RestrictedReason;
    testRunning: boolean;
    motionEnabled: boolean;
}

/** Live sample data sent periodically — 12 bytes on wire */
export interface Sample {
    /** unit: N, scale: 1000 (precision: 1/1000) */
    machineForce: number;
    /** unit: mm, scale: 1000 (precision: 1/1000) */
    machinePosition: number;
    /** unit: mm, scale: 1000 (precision: 1/1000) */
    machineSetpoint: number;
    /** unit: N, scale: 1000 (precision: 1/1000) */
    sampleForce: number;
    /** unit: mm, scale: 1000 (precision: 1/1000) */
    samplePosition: number;
}

/** Binary motion command (G-code move) — 8 bytes on wire */
export interface Move {
    g: GCode;
    /** unit: mm, scale: 1000 (precision: 1/1000) */
    x: number;
    /** unit: mm/s, scale: 1000 (precision: 1/1000) */
    f: number;
    /** unit: ms */
    p: number;
}

/** Firmware-native waveform (G123): oscillate about the current position — 9 bytes on wire */
export interface WaveformMove {
    shape: WaveformShape;
    /** unit: mm, scale: 1000 (precision: 1/1000) */
    amplitude: number;
    /** unit: Hz, scale: 1000 (precision: 1/1000) */
    frequency: number;
    /** unit: count */
    cycles: number;
}

/** Sample written to SD card binary files — 11 bytes on wire */
export interface StoredSample {
    /** unit: N, scale: 1000 (precision: 1/1000) */
    force: number;
    /** unit: mm, scale: 1000 (precision: 1/1000) */
    position: number;
    /** unit: us */
    time: number;
    /** unit: mm, scale: 1000 (precision: 1/1000) */
    setpoint: number;
}

/** Machine profile stored in NVRAM — 68 bytes on wire */
export interface MachineConfiguration {
    name: string;
    /** unit: steps/mm */
    encoderStepsPerMM: number;
    /** unit: steps/mm */
    servoStepsPerMM: number;
    /** unit: N, scale: 1000 (precision: 1/1000) */
    loadCellCapacity: number;
    /** unit: nV/V */
    loadCellSensitivity: number;
    /** unit: nV/V */
    loadCellZeroBalance: number;
    /** unit: mm */
    maxPosition: number;
    /** unit: mm/s */
    maxVelocity: number;
    /** unit: mm/s2 */
    maxAcceleration: number;
    /** unit: N, scale: 1000 (precision: 1/1000) */
    maxForceTensile: number;
    /** unit: mm/s */
    homingVelocity: number;
    /** unit: mm */
    homingOffset: number;
    /** unit: mm */
    jawOffset: number;
}

/** Sample profile — material test limits — 20 bytes on wire */
export interface SampleProfile {
    /** unit: N, scale: 1000 (precision: 1/1000) */
    maxForce: number;
    /** unit: mm/s */
    maxVelocity: number;
    /** unit: mm */
    maxDisplacement: number;
    /** unit: mm */
    sampleWidth: number;
    /** unit: mm */
    sampleThickness: number;
}

/** Firmware version string — 16 bytes on wire */
export interface FirmwareVersion {
    version: string;
}

/** Test run command — references uploaded G-code and assigns test data ID — 14 bytes on wire */
export interface TestRun {
    gcodeId: string;
    testDataId: string;
}

/** Firmware notification message — 101 bytes on wire */
export interface Notification {
    type: NotificationType;
    message: string;
}

// ============================================================
// Wire Sizes
// ============================================================
export const MACHINESTATE_WIRE_SIZE = 2;
export const SAMPLE_WIRE_SIZE = 12;
export const MOVE_WIRE_SIZE = 8;
export const WAVEFORMMOVE_WIRE_SIZE = 9;
export const STOREDSAMPLE_WIRE_SIZE = 11;
export const MACHINECONFIGURATION_WIRE_SIZE = 68;
export const SAMPLEPROFILE_WIRE_SIZE = 20;
export const FIRMWAREVERSION_WIRE_SIZE = 16;
export const TESTRUN_WIRE_SIZE = 14;
export const NOTIFICATION_WIRE_SIZE = 101;

// ============================================================
// Byte-buffer helpers (browser-safe: Uint8Array + DataView, no Node Buffer)
// ============================================================

const _textEncoder = new TextEncoder();
const _textDecoder = new TextDecoder();

/** DataView over a Uint8Array, honoring its byteOffset/byteLength. */
function viewOf(buf: Uint8Array): DataView {
    return new DataView(buf.buffer, buf.byteOffset, buf.byteLength);
}

/** Write a UTF-8 string into `buf` at `offset`, truncated to `maxLen` bytes. */
function writeString(buf: Uint8Array, offset: number, value: string, maxLen: number): void {
    const bytes = _textEncoder.encode(value || '');
    const n = Math.min(bytes.length, maxLen);
    buf.set(bytes.subarray(0, n), offset);
}

/** Read a NUL-terminated UTF-8 string of at most `maxLen` bytes from `buf`. */
function readString(buf: Uint8Array, offset: number, maxLen: number): string {
    const raw = buf.subarray(offset, offset + maxLen);
    const nullIdx = raw.indexOf(0);
    return _textDecoder.decode(raw.subarray(0, nullIdx >= 0 ? nullIdx : maxLen));
}

function packBits(buf: Uint8Array, bitOff: number, bits: number, value: number): void {
    for (let i = 0; i < bits; i++) {
        const byteIdx = Math.floor((bitOff + i) / 8);
        const bitIdx = (bitOff + i) % 8;
        if ((value >>> i) & 1) {
            buf[byteIdx] |= (1 << bitIdx);
        }
    }
}

function unpackBits(buf: Uint8Array, bitOff: number, bits: number): number {
    let value = 0;
    for (let i = 0; i < bits; i++) {
        const byteIdx = Math.floor((bitOff + i) / 8);
        const bitIdx = (bitOff + i) % 8;
        if ((buf[byteIdx] >>> bitIdx) & 1) {
            value |= (1 << i);
        }
    }
    return value >>> 0;  // ensure unsigned
}

// ============================================================
// Encode / Decode Functions
// ============================================================

/**
 * Encode MachineState → 2 bytes.
 * Input values are in unit (see field `unit`); scale is applied to produce wire steps.
 */
export function encodeMachineState(src: MachineState): Uint8Array {
    const buf = new Uint8Array(2);
    packBits(buf, 0, 4, src.faultedReason);
    packBits(buf, 4, 3, src.restrictedReason);
    packBits(buf, 7, 1, src.testRunning ? 1 : 0);
    packBits(buf, 8, 1, src.motionEnabled ? 1 : 0);
    return buf;
}

/**
 * Decode 2 bytes → MachineState.
 * Output values are in unit (see field `unit`); scale is applied as divisor.
 */
export function decodeMachineState(buf: Uint8Array): MachineState {
    return {
        faultedReason: unpackBits(buf, 0, 4) as FaultedReason,
        restrictedReason: unpackBits(buf, 4, 3) as RestrictedReason,
        testRunning: unpackBits(buf, 7, 1) !== 0,
        motionEnabled: unpackBits(buf, 8, 1) !== 0,
    };
}

/**
 * Encode Sample → 12 bytes.
 * Input values are in unit (see field `unit`); scale is applied to produce wire steps.
 */
export function encodeSample(src: Sample): Uint8Array {
    const buf = new Uint8Array(12);
    packBits(buf, 0, 18, Math.round((src.machineForce - (-100)) * 1000));
    packBits(buf, 18, 19, Math.round((src.machinePosition - (-200)) * 1000));
    packBits(buf, 37, 19, Math.round((src.machineSetpoint - (-200)) * 1000));
    packBits(buf, 56, 18, Math.round((src.sampleForce - (-100)) * 1000));
    packBits(buf, 74, 19, Math.round((src.samplePosition - (-200)) * 1000));
    return buf;
}

/**
 * Decode 12 bytes → Sample.
 * Output values are in unit (see field `unit`); scale is applied as divisor.
 */
export function decodeSample(buf: Uint8Array): Sample {
    return {
        machineForce: unpackBits(buf, 0, 18) / 1000 + (-100),
        machinePosition: unpackBits(buf, 18, 19) / 1000 + (-200),
        machineSetpoint: unpackBits(buf, 37, 19) / 1000 + (-200),
        sampleForce: unpackBits(buf, 56, 18) / 1000 + (-100),
        samplePosition: unpackBits(buf, 74, 19) / 1000 + (-200),
    };
}

/**
 * Encode Move → 8 bytes.
 * Input values are in unit (see field `unit`); scale is applied to produce wire steps.
 */
export function encodeMove(src: Move): Uint8Array {
    const buf = new Uint8Array(8);
    packBits(buf, 0, 4, GCODE_VALUE_TO_WIRE[src.g] ?? 0);
    packBits(buf, 4, 22, Math.round((src.x - (-200)) * 1000));
    packBits(buf, 26, 22, Math.round((src.f - (0)) * 1000));
    packBits(buf, 48, 16, Math.round(src.p * 1));
    return buf;
}

/**
 * Decode 8 bytes → Move.
 * Output values are in unit (see field `unit`); scale is applied as divisor.
 */
export function decodeMove(buf: Uint8Array): Move {
    return {
        g: GCODE_WIRE_TO_VALUE[unpackBits(buf, 0, 4)] as GCode,
        x: unpackBits(buf, 4, 22) / 1000 + (-200),
        f: unpackBits(buf, 26, 22) / 1000 + (0),
        p: unpackBits(buf, 48, 16) / 1,
    };
}

/**
 * Encode WaveformMove → 9 bytes.
 * Input values are in unit (see field `unit`); scale is applied to produce wire steps.
 */
export function encodeWaveformMove(src: WaveformMove): Uint8Array {
    const buf = new Uint8Array(9);
    packBits(buf, 0, 1, src.shape);
    packBits(buf, 1, 22, Math.round((src.amplitude - (0)) * 1000));
    packBits(buf, 23, 20, Math.round((src.frequency - (0)) * 1000));
    packBits(buf, 43, 24, Math.round((src.cycles - (1)) * 1));
    return buf;
}

/**
 * Decode 9 bytes → WaveformMove.
 * Output values are in unit (see field `unit`); scale is applied as divisor.
 */
export function decodeWaveformMove(buf: Uint8Array): WaveformMove {
    return {
        shape: unpackBits(buf, 0, 1) as WaveformShape,
        amplitude: unpackBits(buf, 1, 22) / 1000 + (0),
        frequency: unpackBits(buf, 23, 20) / 1000 + (0),
        cycles: unpackBits(buf, 43, 24) / 1 + (1),
    };
}

/**
 * Encode StoredSample → 11 bytes.
 * Input values are in unit (see field `unit`); scale is applied to produce wire steps.
 */
export function encodeStoredSample(src: StoredSample): Uint8Array {
    const buf = new Uint8Array(11);
    packBits(buf, 0, 18, Math.round((src.force - (-100)) * 1000));
    packBits(buf, 18, 19, Math.round((src.position - (-200)) * 1000));
    packBits(buf, 37, 32, Math.round(src.time * 1));
    packBits(buf, 69, 19, Math.round((src.setpoint - (-200)) * 1000));
    return buf;
}

/**
 * Decode 11 bytes → StoredSample.
 * Output values are in unit (see field `unit`); scale is applied as divisor.
 */
export function decodeStoredSample(buf: Uint8Array): StoredSample {
    return {
        force: unpackBits(buf, 0, 18) / 1000 + (-100),
        position: unpackBits(buf, 18, 19) / 1000 + (-200),
        time: unpackBits(buf, 37, 32) / 1,
        setpoint: unpackBits(buf, 69, 19) / 1000 + (-200),
    };
}

/**
 * Encode MachineConfiguration → 68 bytes.
 * Input values are in unit (see field `unit`); scale is applied to produce wire steps.
 */
export function encodeMachineConfiguration(src: MachineConfiguration): Uint8Array {
    const buf = new Uint8Array(68);
    const view = viewOf(buf);
    let offset = 0;
    writeString(buf, offset, src.name, 20);
    offset += 20;
    view.setInt32(offset, Math.round(src.encoderStepsPerMM * 1), true);
    offset += 4;
    view.setInt32(offset, Math.round(src.servoStepsPerMM * 1), true);
    offset += 4;
    view.setInt32(offset, Math.round(src.loadCellCapacity * 1000), true);
    offset += 4;
    view.setInt32(offset, Math.round(src.loadCellSensitivity * 1), true);
    offset += 4;
    view.setInt32(offset, Math.round(src.loadCellZeroBalance * 1), true);
    offset += 4;
    view.setInt32(offset, Math.round(src.maxPosition * 1), true);
    offset += 4;
    view.setInt32(offset, Math.round(src.maxVelocity * 1), true);
    offset += 4;
    view.setInt32(offset, Math.round(src.maxAcceleration * 1), true);
    offset += 4;
    view.setInt32(offset, Math.round(src.maxForceTensile * 1000), true);
    offset += 4;
    view.setInt32(offset, Math.round(src.homingVelocity * 1), true);
    offset += 4;
    view.setInt32(offset, Math.round(src.homingOffset * 1), true);
    offset += 4;
    view.setInt32(offset, Math.round(src.jawOffset * 1), true);
    offset += 4;
    return buf;
}

/**
 * Decode 68 bytes → MachineConfiguration.
 * Output values are in unit (see field `unit`); scale is applied as divisor.
 */
export function decodeMachineConfiguration(buf: Uint8Array): MachineConfiguration {
    const view = viewOf(buf);
    let offset = 0;
    const name = readString(buf, offset, 20);
    offset += 20;
    const encoderStepsPerMM = view.getInt32(offset, true) / 1;
    offset += 4;
    const servoStepsPerMM = view.getInt32(offset, true) / 1;
    offset += 4;
    const loadCellCapacity = view.getInt32(offset, true) / 1000;
    offset += 4;
    const loadCellSensitivity = view.getInt32(offset, true) / 1;
    offset += 4;
    const loadCellZeroBalance = view.getInt32(offset, true) / 1;
    offset += 4;
    const maxPosition = view.getInt32(offset, true) / 1;
    offset += 4;
    const maxVelocity = view.getInt32(offset, true) / 1;
    offset += 4;
    const maxAcceleration = view.getInt32(offset, true) / 1;
    offset += 4;
    const maxForceTensile = view.getInt32(offset, true) / 1000;
    offset += 4;
    const homingVelocity = view.getInt32(offset, true) / 1;
    offset += 4;
    const homingOffset = view.getInt32(offset, true) / 1;
    offset += 4;
    const jawOffset = view.getInt32(offset, true) / 1;
    offset += 4;

    return {
        name,
        encoderStepsPerMM,
        servoStepsPerMM,
        loadCellCapacity,
        loadCellSensitivity,
        loadCellZeroBalance,
        maxPosition,
        maxVelocity,
        maxAcceleration,
        maxForceTensile,
        homingVelocity,
        homingOffset,
        jawOffset,
    };
}

/**
 * Encode SampleProfile → 20 bytes.
 * Input values are in unit (see field `unit`); scale is applied to produce wire steps.
 */
export function encodeSampleProfile(src: SampleProfile): Uint8Array {
    const buf = new Uint8Array(20);
    const view = viewOf(buf);
    let offset = 0;
    view.setUint32(offset, Math.round(src.maxForce * 1000) >>> 0, true);
    offset += 4;
    view.setUint32(offset, Math.round(src.maxVelocity * 1) >>> 0, true);
    offset += 4;
    view.setUint32(offset, Math.round(src.maxDisplacement * 1) >>> 0, true);
    offset += 4;
    view.setUint32(offset, Math.round(src.sampleWidth * 1) >>> 0, true);
    offset += 4;
    view.setUint32(offset, Math.round(src.sampleThickness * 1) >>> 0, true);
    offset += 4;
    return buf;
}

/**
 * Decode 20 bytes → SampleProfile.
 * Output values are in unit (see field `unit`); scale is applied as divisor.
 */
export function decodeSampleProfile(buf: Uint8Array): SampleProfile {
    const view = viewOf(buf);
    let offset = 0;
    const maxForce = view.getUint32(offset, true) / 1000;
    offset += 4;
    const maxVelocity = view.getUint32(offset, true) / 1;
    offset += 4;
    const maxDisplacement = view.getUint32(offset, true) / 1;
    offset += 4;
    const sampleWidth = view.getUint32(offset, true) / 1;
    offset += 4;
    const sampleThickness = view.getUint32(offset, true) / 1;
    offset += 4;

    return {
        maxForce,
        maxVelocity,
        maxDisplacement,
        sampleWidth,
        sampleThickness,
    };
}

/**
 * Encode FirmwareVersion → 16 bytes.
 * Input values are in unit (see field `unit`); scale is applied to produce wire steps.
 */
export function encodeFirmwareVersion(src: FirmwareVersion): Uint8Array {
    const buf = new Uint8Array(16);
    let offset = 0;
    writeString(buf, offset, src.version, 16);
    offset += 16;
    return buf;
}

/**
 * Decode 16 bytes → FirmwareVersion.
 * Output values are in unit (see field `unit`); scale is applied as divisor.
 */
export function decodeFirmwareVersion(buf: Uint8Array): FirmwareVersion {
    let offset = 0;
    const version = readString(buf, offset, 16);
    offset += 16;

    return {
        version,
    };
}

/**
 * Encode TestRun → 14 bytes.
 * Input values are in unit (see field `unit`); scale is applied to produce wire steps.
 */
export function encodeTestRun(src: TestRun): Uint8Array {
    const buf = new Uint8Array(14);
    let offset = 0;
    writeString(buf, offset, src.gcodeId, 7);
    offset += 7;
    writeString(buf, offset, src.testDataId, 7);
    offset += 7;
    return buf;
}

/**
 * Decode 14 bytes → TestRun.
 * Output values are in unit (see field `unit`); scale is applied as divisor.
 */
export function decodeTestRun(buf: Uint8Array): TestRun {
    let offset = 0;
    const gcodeId = readString(buf, offset, 7);
    offset += 7;
    const testDataId = readString(buf, offset, 7);
    offset += 7;

    return {
        gcodeId,
        testDataId,
    };
}

/**
 * Encode Notification → 101 bytes.
 * Input values are in unit (see field `unit`); scale is applied to produce wire steps.
 */
export function encodeNotification(src: Notification): Uint8Array {
    const buf = new Uint8Array(101);
    let offset = 0;
    buf[offset] = src.type;
    offset += 1;
    writeString(buf, offset, src.message, 100);
    offset += 100;
    return buf;
}

/**
 * Decode 101 bytes → Notification.
 * Output values are in unit (see field `unit`); scale is applied as divisor.
 */
export function decodeNotification(buf: Uint8Array): Notification {
    let offset = 0;
    const type = buf[offset] as NotificationType;
    offset += 1;
    const message = readString(buf, offset, 100);
    offset += 100;

    return {
        type,
        message,
    };
}

// ============================================================
// Message Command IDs
// ============================================================
export const MSG_READ_SAMPLE = 0;
export const MSG_READ_STATE = 1;
export const MSG_READ_MACHINE_CONFIGURATION = 2;
export const MSG_READ_FIRMWARE_VERSION = 3;
export const MSG_READ_SAMPLE_PROFILE = 4;
export const MSG_WRITE_MACHINE_CONFIGURATION_WRITE = 0;
export const MSG_WRITE_MOTION_ENABLE = 1;
export const MSG_WRITE_TEST_RUN = 2;
export const MSG_WRITE_MANUAL_MOVE = 3;
export const MSG_WRITE_TEST_MOVE = 4;
export const MSG_WRITE_TEST_WAVEFORM = 8;
export const MSG_WRITE_SAMPLE_PROFILE_WRITE = 5;
export const MSG_WRITE_GAUGE_LENGTH = 6;
export const MSG_WRITE_GAUGE_FORCE = 7;
export const MSG_WRITE_FILE_DOWNLOAD = 9;

// ============================================================
// Periodic Message Periods (ms)
// ============================================================
export const MSG_SAMPLE_PERIOD_MS = 10;
export const MSG_STATE_PERIOD_MS = 1000;

// ============================================================
// Message Priorities (host scheduling hint; not on the wire)
// ============================================================
export const MSG_SAMPLE_PRIORITY = 'low' as const;
export const MSG_STATE_PRIORITY = 'low' as const;
export const MSG_MACHINE_CONFIGURATION_PRIORITY = 'high' as const;
export const MSG_FIRMWARE_VERSION_PRIORITY = 'high' as const;
export const MSG_SAMPLE_PROFILE_PRIORITY = 'high' as const;
export const MSG_MACHINE_CONFIGURATION_WRITE_PRIORITY = 'high' as const;
export const MSG_MOTION_ENABLE_PRIORITY = 'high' as const;
export const MSG_TEST_RUN_PRIORITY = 'high' as const;
export const MSG_MANUAL_MOVE_PRIORITY = 'high' as const;
export const MSG_TEST_MOVE_PRIORITY = 'high' as const;
export const MSG_TEST_WAVEFORM_PRIORITY = 'high' as const;
export const MSG_SAMPLE_PROFILE_WRITE_PRIORITY = 'high' as const;
export const MSG_GAUGE_LENGTH_PRIORITY = 'high' as const;
export const MSG_GAUGE_FORCE_PRIORITY = 'high' as const;
export const MSG_FILE_DOWNLOAD_PRIORITY = 'high' as const;

// ============================================================
// Typed message facade
// ============================================================
// Bridges the generic runtime (raw command id + payload bytes) to typed,
// decoded payloads — the "last mile" so callers don't hand-map ids to structs.

/** A decoded inbound payload (a DATA response or an async notification). */
export type Inbound =
    | { kind: 'sample'; value: Sample }
    | { kind: 'state'; value: MachineState }
    | { kind: 'machine_configuration'; value: MachineConfiguration }
    | { kind: 'firmware_version'; value: FirmwareVersion }
    | { kind: 'sample_profile'; value: SampleProfile }
    | { kind: 'file_download'; value: StoredSample }
    | { kind: 'notification'; value: Notification }
    | { kind: 'unknown'; command: number; payload: Uint8Array };

/** Decode a DATA response for `command` into its typed payload. */
export function decodeData(command: number, payload: Uint8Array): Inbound {
    switch (command) {
        case 0: return { kind: 'sample', value: decodeSample(payload) };
        case 1: return { kind: 'state', value: decodeMachineState(payload) };
        case 2: return { kind: 'machine_configuration', value: decodeMachineConfiguration(payload) };
        case 3: return { kind: 'firmware_version', value: decodeFirmwareVersion(payload) };
        case 4: return { kind: 'sample_profile', value: decodeSampleProfile(payload) };
        case 9: return { kind: 'file_download', value: decodeStoredSample(payload) };
        default: return { kind: 'unknown', command, payload };
    }
}
