#!/usr/bin/env python3
"""Emit trans_ stubs for every DecodeTree pattern the skeleton does not model.

The decoder has ~482 patterns and every one needs a trans_ function to link.
Anything not hand-written in translate.c stops the CPU rather than silently
doing the wrong thing: during bring-up a missing instruction must be noticed,
not drifted past.

usage: gen_stubs.py <insn.decode> <decode-insn.c.inc> <out.c.inc>
"""
import re
import sys

decode_c = open(sys.argv[2]).read()
names = re.findall(r"^static bool trans_(\w+)\(DisasContext \*ctx, arg_(\w+) \*a\);",
                   decode_c, re.M)
hand = set(re.findall(r"^\s*(?:static bool |GEN_ALU\()trans_?(\w+)",
                      open(sys.argv[3] if len(sys.argv) > 4 else "/dev/null").read(), re.M))

impl = {"mov", "and", "or", "xor", "not", "add", "sub",
        "sar", "cmp", "cmps", "test", "testn", "neg", "abs",
        "shl", "shr", "rol", "ror", "addx", "subx", "adds", "subs", "fge", "fle", "decod", "encod", "ones", "muxc", "muxnc", "muxz", "muxnz"}
out = ["/* @generated by gen_stubs.py -- DO NOT EDIT. */", ""]
n = 0
for name, arg in names:
    if name in impl:
        continue
    out.append("static bool trans_%s(DisasContext *ctx, arg_%s *a)\n"
               "{\n    return p2_unimpl(ctx);\n}" % (name, arg))
    n += 1
open(sys.argv[3] if len(sys.argv) == 4 else sys.argv[-1], "w").write("\n".join(out) + "\n")
print("%d stubs, %d hand-implemented" % (n, len(impl)), file=sys.stderr)
