#!/usr/bin/env python3
"""Emit trans_ stubs for every DecodeTree pattern the skeleton does not model.

The decoder has ~482 patterns and every one needs a trans_ function to link.
Anything not hand-written in translate.c stops the CPU rather than silently
doing the wrong thing: during bring-up a missing instruction must be noticed,
not drifted past.

usage: gen_stubs.py <insn.decode> <decode-insn.c.inc> <out.c.inc>
"""
import re
import sys

decode_c = open(sys.argv[2]).read()
names = re.findall(r"^static bool trans_(\w+)\(DisasContext \*ctx, arg_(\w+) \*a\);",
                   decode_c, re.M)
hand = set(re.findall(r"^\s*(?:static bool |GEN_ALU\()trans_?(\w+)",
                      open(sys.argv[3] if len(sys.argv) > 4 else "/dev/null").read(), re.M))

impl = {"mov", "and", "or", "xor", "not", "add", "sub",
        "sar", "cmp", "cmps", "test", "testn", "neg", "abs",
        "shl", "shr", "rol", "ror", "addx", "subx", "adds", "subs", "fge", "fle", "decod", "encod", "ones", "muxc", "muxnc", "muxz", "muxnz",
        "zerox", "signx", "sumc", "sumnc", "sumz", "sumnz", "getbyte", "cmpr", "incmod", "decmod",
        "negc", "negnc", "negz", "negnz", "cmpsub",
        "rcl", "rcr", "bitl", "bith", "testb", "testb_2", "testb_3", "testbn", "testbn_2", "testbn_3",
        "jmp", "jmp_2", "jmp_3", "call", "call_2", "ret", "jmprel", "jmprel_2", "push", "pop", "djnz", "djz", "djf", "djnf", "tjz", "tjnz", "callpa", "callpa_2", "callpb", "callpb_2", "calld", "nop_zero",
        "rdbyte", "rdword", "rdlong", "wrbyte", "wrbyte_2", "wrword", "wrword_2", "wrlong", "wrlong_2",
        "augs", "augd", "setq", "setq2", "getct", "rev", "altd", "alts",
        "wrpin", "wrpin_2", "wxpin", "wxpin_2", "wypin", "wypin_2", "rdpin", "rdpin_2", "rqpin", "rqpin_2", "testp", "testp_2", "testp_3", "waitx", "waitx_2", "setq_2", "setq2_2", "dirl", "dirl_2", "dirh", "dirh_2", "fltl", "fltl_2", "flth", "flth_2", "drvl", "drvl_2", "drvh", "drvh_2", "outl", "outl_2", "outh", "outh_2", "drvc", "drvc_2", "drvnc", "drvnc_2", "drvz", "drvz_2", "drvnz", "drvnz_2", "drvnot", "drvnot_2",
        "fges", "fles", "subr", "andn", "movbyts", "bitnot", "bitc", "bitnc", "bitz", "bitnz", "wrc", "wrnc", "wrz", "wrnz", "wrc_2", "wrnc_2", "wrz_2", "wrnz_2",
        "qmul", "qmul_2", "qdiv", "qdiv_2", "qsqrt", "qsqrt_2", "qrotate", "qrotate_2", "getqx", "getqx_2", "getqy", "getqy_2", "locknew", "locknew_2", "lockret", "lockret_2", "locktry", "locktry_2", "lockrel", "lockrel_2", "cogid", "cogid_2", "cogstop", "cogstop_2", "hubset", "hubset_2", "addct1", "addct2", "addct3", "waitct1",
        "rep", "rep_2", "skip", "skip_2", "coginit"}
out = ["/* @generated by gen_stubs.py -- DO NOT EDIT. */", ""]
n = 0
for name, arg in names:
    if name in impl:
        continue
    out.append("static bool trans_%s(DisasContext *ctx, arg_%s *a)\n"
               "{\n    return p2_unimpl(ctx);\n}" % (name, arg))
    n += 1
open(sys.argv[3] if len(sys.argv) == 4 else sys.argv[-1], "w").write("\n".join(out) + "\n")
print("%d stubs, %d hand-implemented" % (n, len(impl)), file=sys.stderr)
