#ifndef HW_PINS_H
#define HW_PINS_H
typedef enum
{
    HW_PIN_FORCE_GAUGE_RX = 0,
    HW_PIN_FORCE_GAUGE_TX = 2,

    HW_PIN_SERVO_ENA = 6,
    HW_PIN_SERVO_PUL = 8,
    HW_PIN_SERVO_DIR = 7,
    HW_PIN_SERVO_RDY = 5,

    HW_PIN_SERVO_ENCODER_A = 9,
    HW_PIN_SERVO_ENCODER_B = 10,
    HW_PIN_SERVO_ENCODER_Z = 11,
    HW_PIN_SERVO_ENCODER_ZI = 12,

    HW_PIN_NAVKEY_INT = 13,
    HW_PIN_NAVKEY_SCL = 14,
    HW_PIN_NAVKEY_SDA = 15,

    HW_PIN_ESD_UPPER = 16,
    HW_PIN_ESD_LOWER = 17,
    HW_PIN_ESD_SWITCH = 18,
    HW_PIN_ENDSTOP_UPPER = 19,
    HW_PIN_ENDSTOP_LOWER = 20,
    HW_PIN_ENDSTOP_DOOR = 21,
    HW_PIN_ESD_POWER = 22,
    HW_PIN_CHARGE_PUMP = 28,

    HW_PIN_RPI_RX = 53,
    HW_PIN_RPI_TX = 55,

    HW_PIN_MAIN_RX = 63,
    HW_PIN_MAIN_TX = 62,
    
    // SD Card pins (P2 Edge Module standard configuration)
    HW_PIN_SD_CLK = 61,
    HW_PIN_SD_MOSI = 60,
    HW_PIN_SD_MISO = 59,
    HW_PIN_SD_CS = 58,
} HW_pin_E;
#endif /* HW_PINS_H */
