kibot:
  version: 1

preflight:
  run_erc: false
  run_drc: false
  check_zone_fills: false
  ignore_unconnected: false

outputs:
  # Gerber files for manufacturing
  - name: 'gerbers'
    comment: "Gerber files for PCB manufacturing"
    type: gerber
    dir: Manufacturing/gerbers
    options:
      exclude_edge_layer: true
      exclude_pads_from_silkscreen: false
      use_aux_axis_as_origin: false
      plot_sheet_reference: false
      plot_footprint_refs: true
      plot_footprint_values: true
      force_plot_invisible_refs_vals: false
      tent_vias: true
      line_width: 0.1
      subtract_mask_from_silk: false
      use_protel_extensions: false
      gerber_precision: 4.6
      create_gerber_job_file: true
      output: "%f.%x"
      use_gerber_x2_attributes: true
      use_gerber_net_attributes: true

  # Drill files
  - name: 'drill'
    comment: "Excellon drill files"
    type: excellon
    dir: Manufacturing/gerbers
    options:
      pth_and_npth_single_file: false
      pth_id: ''
      npth_id: '-NPTH'
      metric_units: true
      output: "%f%i.drl"

  # Pick and place files
  - name: 'position'
    comment: "Pick and place files for assembly"
    type: position
    dir: Manufacturing
    options:
      format: ASCII
      units: millimeters
      separate_files_for_front_and_back: true
      only_smd: true
      output: "%f_cpl%i.%x"

  # Bill of Materials
  - name: 'bom'
    comment: "Bill of Materials in CSV format"
    type: bom
    dir: Manufacturing
    options:
      output: '%f_bom.%x'
      ref_separator: ','
      columns:
        - Row
        - field: References
          name: Designator
        - field: Value
          name: Comment
        - field: Footprint
          name: Footprint
        - field: Quantity Per PCB
          name: Quantity
        - field: Datasheet
          name: Datasheet
        - field: LCSC
          name: LCSC Part Number
      csv:
        hide_pcb_info: true
        hide_stats_info: true
        quote_all: true

  # Interactive HTML BOM
  - name: 'ibom'
    comment: "Interactive HTML BOM"
    type: ibom
    dir: Documentation
    options:
      blacklist: 'DNF*'
      include_tracks: false
      include_nets: false
      sort_order: 'C,R,L,D,U,Y,X,F,SW,A'
      output: '%f_ibom.%x'

  # Schematic PDF
  - name: 'schematic_pdf'
    comment: "Schematic in PDF format"
    type: pdf_sch_print
    dir: Documentation
    options:
      output: '%f_schematic.%x'

  # PCB PDF prints
  - name: 'pcb_top_pdf'
    comment: "PCB top view PDF"
    type: pcb_print
    dir: Documentation
    options:
      output: '%f_pcb_top.%x'
      format: PDF
      plot_sheet_reference: false
      layers:
        - layer: F.Cu
        - layer: F.Mask
        - layer: F.Silkscreen
        - layer: Edge.Cuts

  - name: 'pcb_bottom_pdf'
    comment: "PCB bottom view PDF"
    type: pcb_print
    dir: Documentation
    options:
      output: '%f_pcb_bottom.%x'
      format: PDF
      plot_sheet_reference: false
      layers:
        - layer: B.Cu
        - layer: B.Mask
        - layer: B.Silkscreen
        - layer: Edge.Cuts

  # PCB renders (3D-like view)
  - name: 'pcb_top_render'
    comment: "PCB top 3D render"
    type: pcbdraw
    dir: Documentation/renders
    options:
      format: svg
      style: set-white-enig
      output: '%f_top.%x'

  - name: 'pcb_bottom_render'
    comment: "PCB bottom 3D render"  
    type: pcbdraw
    dir: Documentation/renders
    options:
      format: svg
      style: set-white-enig
      bottom: true
      output: '%f_bottom.%x'

  # 3D model export
  - name: 'step'
    comment: "3D model in STEP format"
    type: step
    dir: Manufacturing
    options:
      output: '%f.%x'
      origin: grid

  # 3D Renderings - Multiple views
  - name: '3d_top'
    comment: "3D render - top view"
    type: render_3d
    dir: Documentation/3d_renders
    options:
      output: '%f_3d_top.%x'
      ray_tracing: true
      orthographic: false
      view: top
      zoom: 0
      rotate_x: 0
      rotate_y: 0
      rotate_z: 0
      width: 1920
      height: 1080
      background1: '#66667F'
      background2: '#CCCCE5'

  - name: '3d_bottom'
    comment: "3D render - bottom view"
    type: render_3d
    dir: Documentation/3d_renders
    options:
      output: '%f_3d_bottom.%x'
      ray_tracing: true
      orthographic: false
      view: bottom
      zoom: 0
      rotate_x: 0
      rotate_y: 0
      rotate_z: 0
      width: 1920
      height: 1080
      background1: '#66667F'
      background2: '#CCCCE5'

  - name: '3d_front'
    comment: "3D render - front view"
    type: render_3d
    dir: Documentation/3d_renders
    options:
      output: '%f_3d_front.%x'
      ray_tracing: true
      orthographic: false
      view: front
      zoom: 0
      rotate_x: 0
      rotate_y: 0
      rotate_z: 0
      width: 1920
      height: 1080
      background1: '#66667F'
      background2: '#CCCCE5'

  - name: '3d_back'
    comment: "3D render - back view"
    type: render_3d
    dir: Documentation/3d_renders
    options:
      output: '%f_3d_back.%x'
      ray_tracing: true
      orthographic: false
      view: rear
      zoom: 0
      rotate_x: 0
      rotate_y: 0
      rotate_z: 0
      width: 1920
      height: 1080
      background1: '#66667F'
      background2: '#CCCCE5'

  - name: '3d_left'
    comment: "3D render - left side view"
    type: render_3d
    dir: Documentation/3d_renders
    options:
      output: '%f_3d_left.%x'
      ray_tracing: true
      orthographic: false
      view: left
      zoom: 0
      rotate_x: 0
      rotate_y: 0
      rotate_z: 0
      width: 1920
      height: 1080
      background1: '#66667F'
      background2: '#CCCCE5'

  - name: '3d_right'
    comment: "3D render - right side view"
    type: render_3d
    dir: Documentation/3d_renders
    options:
      output: '%f_3d_right.%x'
      ray_tracing: true
      orthographic: false
      view: right
      zoom: 0
      rotate_x: 0
      rotate_y: 0
      rotate_z: 0
      width: 1920
      height: 1080
      background1: '#66667F'
      background2: '#CCCCE5'

  - name: '3d_isometric'
    comment: "3D render - isometric view"
    type: render_3d
    dir: Documentation/3d_renders
    options:
      output: '%f_3d_isometric.%x'
      ray_tracing: true
      orthographic: false
      view: z
      zoom: 0
      rotate_x: 30
      rotate_y: 0
      rotate_z: 45
      width: 1920
      height: 1080
      background1: '#66667F'
      background2: '#CCCCE5'

  # Compressed gerber package for manufacturers
  - name: 'gerber_zip'
    comment: "Compressed gerber package"
    type: compress
    dir: Manufacturing
    options:
      files:
        - from_output: gerbers
          dest: /
        - from_output: drill
          dest: /
        - from_output: position
          dest: /
      output: '%f_gerbers.%x'

  # Documentation package
  - name: 'docs_zip'
    comment: "Documentation package"
    type: compress
    dir: .
    options:
      files:
        - from_output: schematic_pdf
          dest: /
        - from_output: pcb_top_pdf
          dest: /
        - from_output: pcb_bottom_pdf
          dest: /
        - from_output: ibom
          dest: /
        - from_output: bom
          dest: /
        - from_output: 3d_top
          dest: /3d_renders/
        - from_output: 3d_bottom
          dest: /3d_renders/
        - from_output: 3d_front
          dest: /3d_renders/
        - from_output: 3d_back
          dest: /3d_renders/
        - from_output: 3d_left
          dest: /3d_renders/
        - from_output: 3d_right
          dest: /3d_renders/
        - from_output: 3d_isometric
          dest: /3d_renders/
      output: '%f_documentation.%x' 