//! Auto-generated protocol definitions — DO NOT EDIT
//!
//! Generated by ProtoEmb code generator from YAML schema
//! Protocol version: 1

#![allow(dead_code, clippy::identity_op, clippy::excessive_precision)]

/// Protocol version
pub const PROTOCOL_VERSION: u32 = 1;

// Node IDs (for multi-node / addressed framing).
pub const NODE_UI: u8 = 0;
pub const NODE_MADCORE: u8 = 1;


// ============================================================
// Enums
// ============================================================

/// Machine fault codes
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum FaultedReason {
    None = 0,
    Cog = 1,
    Watchdog = 2,
    EsdPower = 3,
    EsdSwitch = 4,
    EsdUpper = 5,
    EsdLower = 6,
    ServoCommunication = 7,
    ForceGaugeCommunication = 8,
}

impl FaultedReason {
    /// Number of variants
    pub const COUNT: usize = 9;

    /// Bits needed on wire
    pub const BITS: u32 = 4;

    /// Convert from wire index to enum
    pub fn from_wire(v: u8) -> Option<Self> {
        match v {
            0 => Some(Self::None),
            1 => Some(Self::Cog),
            2 => Some(Self::Watchdog),
            3 => Some(Self::EsdPower),
            4 => Some(Self::EsdSwitch),
            5 => Some(Self::EsdUpper),
            6 => Some(Self::EsdLower),
            7 => Some(Self::ServoCommunication),
            8 => Some(Self::ForceGaugeCommunication),
            _ => None,
        }
    }

    /// Convert enum to wire index
    pub fn to_wire(self) -> u8 {
        self as u8
    }
}

impl Default for FaultedReason {
    fn default() -> Self {
        Self::None
    }
}

/// Motion restriction codes
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum RestrictedReason {
    None = 0,
    SampleLength = 1,
    SampleTension = 2,
    MachineTension = 3,
    UpperEndstop = 4,
    LowerEndstop = 5,
    Door = 6,
}

impl RestrictedReason {
    /// Number of variants
    pub const COUNT: usize = 7;

    /// Bits needed on wire
    pub const BITS: u32 = 3;

    /// Convert from wire index to enum
    pub fn from_wire(v: u8) -> Option<Self> {
        match v {
            0 => Some(Self::None),
            1 => Some(Self::SampleLength),
            2 => Some(Self::SampleTension),
            3 => Some(Self::MachineTension),
            4 => Some(Self::UpperEndstop),
            5 => Some(Self::LowerEndstop),
            6 => Some(Self::Door),
            _ => None,
        }
    }

    /// Convert enum to wire index
    pub fn to_wire(self) -> u8 {
        self as u8
    }
}

impl Default for RestrictedReason {
    fn default() -> Self {
        Self::None
    }
}

/// Motion subsystem state
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum MotionState {
    Disabled = 0,
    Waiting = 1,
    Moving = 2,
}

impl MotionState {
    /// Number of variants
    pub const COUNT: usize = 3;

    /// Bits needed on wire
    pub const BITS: u32 = 2;

    /// Convert from wire index to enum
    pub fn from_wire(v: u8) -> Option<Self> {
        match v {
            0 => Some(Self::Disabled),
            1 => Some(Self::Waiting),
            2 => Some(Self::Moving),
            _ => None,
        }
    }

    /// Convert enum to wire index
    pub fn to_wire(self) -> u8 {
        self as u8
    }
}

impl Default for MotionState {
    fn default() -> Self {
        Self::Disabled
    }
}

/// G-code command identifiers
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum GCode {
    RapidMove = 0,
    LinearMove = 1,
    CwArc = 2,
    CcwArc = 3,
    Dwell = 4,
    Home = 5,
    Absolute = 6,
    Incremental = 7,
    Stop = 8,
    Waveform = 9,
}

impl GCode {
    /// Number of variants
    pub const COUNT: usize = 10;

    /// Bits needed on wire
    pub const BITS: u32 = 4;

    /// Convert from wire index to enum
    pub fn from_wire(v: u8) -> Option<Self> {
        match v {
            0 => Some(Self::RapidMove),
            1 => Some(Self::LinearMove),
            2 => Some(Self::CwArc),
            3 => Some(Self::CcwArc),
            4 => Some(Self::Dwell),
            5 => Some(Self::Home),
            6 => Some(Self::Absolute),
            7 => Some(Self::Incremental),
            8 => Some(Self::Stop),
            9 => Some(Self::Waveform),
            _ => None,
        }
    }

    /// Convert enum to wire index
    pub fn to_wire(self) -> u8 {
        self as u8
    }

    /// Remap: wire index → actual value
    pub fn to_value(self) -> u8 {
        const TABLE: [u8; 10] = [
            0,  // RAPID_MOVE
            1,  // LINEAR_MOVE
            2,  // CW_ARC
            3,  // CCW_ARC
            4,  // DWELL
            28,  // HOME
            90,  // ABSOLUTE
            91,  // INCREMENTAL
            122,  // STOP
            123,  // WAVEFORM
        ];
        TABLE[self as usize]
    }

    /// Remap: actual value → wire index
    pub fn from_value(v: u8) -> Option<Self> {
        match v {
            0 => Some(Self::RapidMove),
            1 => Some(Self::LinearMove),
            2 => Some(Self::CwArc),
            3 => Some(Self::CcwArc),
            4 => Some(Self::Dwell),
            28 => Some(Self::Home),
            90 => Some(Self::Absolute),
            91 => Some(Self::Incremental),
            122 => Some(Self::Stop),
            123 => Some(Self::Waveform),
            _ => None,
        }
    }
}

impl Default for GCode {
    fn default() -> Self {
        Self::RapidMove
    }
}

/// Position-vs-time waveform function (firmware-native G123)
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum WaveformShape {
    Sine = 0,
    Triangle = 1,
}

impl WaveformShape {
    /// Number of variants
    pub const COUNT: usize = 2;

    /// Bits needed on wire
    pub const BITS: u32 = 1;

    /// Convert from wire index to enum
    pub fn from_wire(v: u8) -> Option<Self> {
        match v {
            0 => Some(Self::Sine),
            1 => Some(Self::Triangle),
            _ => None,
        }
    }

    /// Convert enum to wire index
    pub fn to_wire(self) -> u8 {
        self as u8
    }
}

impl Default for WaveformShape {
    fn default() -> Self {
        Self::Sine
    }
}

/// Notification severity levels
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum NotificationType {
    Message = 0,
    Info = 1,
    Warning = 2,
    Error = 3,
    Success = 4,
}

impl NotificationType {
    /// Number of variants
    pub const COUNT: usize = 5;

    /// Bits needed on wire
    pub const BITS: u32 = 3;

    /// Convert from wire index to enum
    pub fn from_wire(v: u8) -> Option<Self> {
        match v {
            0 => Some(Self::Message),
            1 => Some(Self::Info),
            2 => Some(Self::Warning),
            3 => Some(Self::Error),
            4 => Some(Self::Success),
            _ => None,
        }
    }

    /// Convert enum to wire index
    pub fn to_wire(self) -> u8 {
        self as u8
    }
}

impl Default for NotificationType {
    fn default() -> Self {
        Self::Message
    }
}

/// Data logging state
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum LoggingState {
    Idle = 0,
    Running = 1,
    Stopping = 2,
}

impl LoggingState {
    /// Number of variants
    pub const COUNT: usize = 3;

    /// Bits needed on wire
    pub const BITS: u32 = 2;

    /// Convert from wire index to enum
    pub fn from_wire(v: u8) -> Option<Self> {
        match v {
            0 => Some(Self::Idle),
            1 => Some(Self::Running),
            2 => Some(Self::Stopping),
            _ => None,
        }
    }

    /// Convert enum to wire index
    pub fn to_wire(self) -> u8 {
        self as u8
    }
}

impl Default for LoggingState {
    fn default() -> Self {
        Self::Idle
    }
}


// ============================================================
// Struct Wire Sizes
// ============================================================
/// Wire size for MachineState (packed)
pub const MACHINESTATE_WIRE_SIZE: usize = 2;
/// Wire size for Sample (packed)
pub const SAMPLE_WIRE_SIZE: usize = 12;
/// Wire size for Move (packed)
pub const MOVE_WIRE_SIZE: usize = 8;
/// Wire size for WaveformMove (packed)
pub const WAVEFORMMOVE_WIRE_SIZE: usize = 9;
/// Wire size for StoredSample (packed)
pub const STOREDSAMPLE_WIRE_SIZE: usize = 11;
/// Wire size for MachineConfiguration (aligned)
pub const MACHINECONFIGURATION_WIRE_SIZE: usize = 64;
/// Wire size for SampleProfile (aligned)
pub const SAMPLEPROFILE_WIRE_SIZE: usize = 20;
/// Wire size for FirmwareVersion (aligned)
pub const FIRMWAREVERSION_WIRE_SIZE: usize = 16;
/// Wire size for TestRun (aligned)
pub const TESTRUN_WIRE_SIZE: usize = 14;
/// Wire size for Notification (aligned)
pub const NOTIFICATION_WIRE_SIZE: usize = 101;

// ============================================================
// Structs
// ============================================================

/// Machine state flags and status (packed, 2 bytes on wire)
#[derive(Debug, Clone, Default, PartialEq)]
pub struct MachineState {
    pub faulted_reason: FaultedReason,
    pub restricted_reason: RestrictedReason,
    pub test_running: bool,
    pub motion_enabled: bool,
}

impl MachineState {
    pub const WIRE_SIZE: usize = 2;

    /// Encode to wire bytes (2 bytes).
    /// Input values are in the agreed `unit`; scale multiplied during bit packing.
    pub fn encode(&self) -> [u8; 2] {
        let mut buf = [0u8; 2];
        pack_bits(&mut buf, 0, 4, self.faulted_reason.to_wire() as u32);
        pack_bits(&mut buf, 4, 3, self.restricted_reason.to_wire() as u32);
        pack_bits(&mut buf, 7, 1, if self.test_running { 1 } else { 0 });
        pack_bits(&mut buf, 8, 1, if self.motion_enabled { 1 } else { 0 });
        buf
    }

    /// Decode from wire bytes.
    /// Output values are in the agreed `unit`; scale divided during bit unpacking.
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < 2 {
            return None;
        }
        Some(Self {
            faulted_reason: FaultedReason::from_wire(unpack_bits(buf, 0, 4) as u8)
                .unwrap_or_default(),
            restricted_reason: RestrictedReason::from_wire(unpack_bits(buf, 4, 3) as u8)
                .unwrap_or_default(),
            test_running: unpack_bits(buf, 7, 1) != 0,
            motion_enabled: unpack_bits(buf, 8, 1) != 0,
        })
    }
}

/// Live sample data sent periodically (packed, 12 bytes on wire)
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Sample {
    pub machine_force: i32,
    pub machine_position: i32,
    pub machine_setpoint: i32,
    pub sample_force: i32,
    pub sample_position: i32,
}

impl Sample {
    pub const WIRE_SIZE: usize = 12;

    /// Encode to wire bytes (12 bytes).
    /// Input values are in the agreed `unit`; scale multiplied during bit packing.
    pub fn encode(&self) -> [u8; 12] {
        let mut buf = [0u8; 12];
        pack_bits(&mut buf, 0, 18, ((self.machine_force - (-100i32)).wrapping_mul(1000i32)) as u32);
        pack_bits(&mut buf, 18, 19, ((self.machine_position - (-200i32)).wrapping_mul(1000i32)) as u32);
        pack_bits(&mut buf, 37, 19, ((self.machine_setpoint - (-200i32)).wrapping_mul(1000i32)) as u32);
        pack_bits(&mut buf, 56, 18, ((self.sample_force - (-100i32)).wrapping_mul(1000i32)) as u32);
        pack_bits(&mut buf, 74, 19, ((self.sample_position - (-200i32)).wrapping_mul(1000i32)) as u32);
        buf
    }

    /// Decode from wire bytes.
    /// Output values are in the agreed `unit`; scale divided during bit unpacking.
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < 12 {
            return None;
        }
        Some(Self {
            machine_force: (unpack_bits(buf, 0, 18) as i32) / 1000i32 + (-100i32),
            machine_position: (unpack_bits(buf, 18, 19) as i32) / 1000i32 + (-200i32),
            machine_setpoint: (unpack_bits(buf, 37, 19) as i32) / 1000i32 + (-200i32),
            sample_force: (unpack_bits(buf, 56, 18) as i32) / 1000i32 + (-100i32),
            sample_position: (unpack_bits(buf, 74, 19) as i32) / 1000i32 + (-200i32),
        })
    }
}

/// Binary motion command (G-code move) (packed, 8 bytes on wire)
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Move {
    pub g: GCode,
    pub x: i32,
    pub f: i32,
    pub p: u32,
}

impl Move {
    pub const WIRE_SIZE: usize = 8;

    /// Encode to wire bytes (8 bytes).
    /// Input values are in the agreed `unit`; scale multiplied during bit packing.
    pub fn encode(&self) -> [u8; 8] {
        let mut buf = [0u8; 8];
        pack_bits(&mut buf, 0, 4, self.g.to_wire() as u32);
        pack_bits(&mut buf, 4, 22, ((self.x - (-200i32)).wrapping_mul(1000i32)) as u32);
        pack_bits(&mut buf, 26, 22, ((self.f - (0i32)).wrapping_mul(1000i32)) as u32);
        pack_bits(&mut buf, 48, 16, self.p);
        buf
    }

    /// Decode from wire bytes.
    /// Output values are in the agreed `unit`; scale divided during bit unpacking.
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < 8 {
            return None;
        }
        Some(Self {
            g: GCode::from_wire(unpack_bits(buf, 0, 4) as u8)
                .unwrap_or_default(),
            x: (unpack_bits(buf, 4, 22) as i32) / 1000i32 + (-200i32),
            f: (unpack_bits(buf, 26, 22) as i32) / 1000i32 + (0i32),
            p: unpack_bits(buf, 48, 16),
        })
    }
}

/// Firmware-native waveform (G123): oscillate about the current position (packed, 9 bytes on wire)
#[derive(Debug, Clone, Default, PartialEq)]
pub struct WaveformMove {
    pub shape: WaveformShape,
    pub amplitude: i32,
    pub frequency: i32,
    pub cycles: u32,
}

impl WaveformMove {
    pub const WIRE_SIZE: usize = 9;

    /// Encode to wire bytes (9 bytes).
    /// Input values are in the agreed `unit`; scale multiplied during bit packing.
    pub fn encode(&self) -> [u8; 9] {
        let mut buf = [0u8; 9];
        pack_bits(&mut buf, 0, 1, self.shape.to_wire() as u32);
        pack_bits(&mut buf, 1, 22, ((self.amplitude - (0i32)).wrapping_mul(1000i32)) as u32);
        pack_bits(&mut buf, 23, 20, ((self.frequency - (0i32)).wrapping_mul(1000i32)) as u32);
        pack_bits(&mut buf, 43, 24, (self.cycles.wrapping_sub(1u32)));
        buf
    }

    /// Decode from wire bytes.
    /// Output values are in the agreed `unit`; scale divided during bit unpacking.
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < 9 {
            return None;
        }
        Some(Self {
            shape: WaveformShape::from_wire(unpack_bits(buf, 0, 1) as u8)
                .unwrap_or_default(),
            amplitude: (unpack_bits(buf, 1, 22) as i32) / 1000i32 + (0i32),
            frequency: (unpack_bits(buf, 23, 20) as i32) / 1000i32 + (0i32),
            cycles: unpack_bits(buf, 43, 24).wrapping_add(1u32),
        })
    }
}

/// Sample written to SD card binary files (packed, 11 bytes on wire)
#[derive(Debug, Clone, Default, PartialEq)]
pub struct StoredSample {
    pub force: i32,
    pub position: i32,
    pub time: u32,
    pub setpoint: i32,
}

impl StoredSample {
    pub const WIRE_SIZE: usize = 11;

    /// Encode to wire bytes (11 bytes).
    /// Input values are in the agreed `unit`; scale multiplied during bit packing.
    pub fn encode(&self) -> [u8; 11] {
        let mut buf = [0u8; 11];
        pack_bits(&mut buf, 0, 18, ((self.force - (-100i32)).wrapping_mul(1000i32)) as u32);
        pack_bits(&mut buf, 18, 19, ((self.position - (-200i32)).wrapping_mul(1000i32)) as u32);
        pack_bits(&mut buf, 37, 32, self.time);
        pack_bits(&mut buf, 69, 19, ((self.setpoint - (-200i32)).wrapping_mul(1000i32)) as u32);
        buf
    }

    /// Decode from wire bytes.
    /// Output values are in the agreed `unit`; scale divided during bit unpacking.
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < 11 {
            return None;
        }
        Some(Self {
            force: (unpack_bits(buf, 0, 18) as i32) / 1000i32 + (-100i32),
            position: (unpack_bits(buf, 18, 19) as i32) / 1000i32 + (-200i32),
            time: unpack_bits(buf, 37, 32),
            setpoint: (unpack_bits(buf, 69, 19) as i32) / 1000i32 + (-200i32),
        })
    }
}

/// Machine profile stored in NVRAM (aligned, 64 bytes on wire)
#[derive(Debug, Clone, Default, PartialEq)]
pub struct MachineConfiguration {
    pub name: String,
    pub encoder_steps_per_mm: i32,
    pub servo_steps_per_mm: i32,
    pub force_gauge_n_per_step: i32,
    pub force_gauge_zero_offset: i32,
    pub max_position: i32,
    pub max_velocity: i32,
    pub max_acceleration: i32,
    pub max_force_tensile: i32,
    pub homing_velocity: i32,
    pub homing_offset: i32,
    pub jaw_offset: i32,
}

impl MachineConfiguration {
    pub const WIRE_SIZE: usize = 64;

    /// Encode to wire bytes (64 bytes).
    /// Input values are in the agreed `unit`; scale multiplied during bit packing.
    pub fn encode(&self) -> [u8; 64] {
        let mut buf = [0u8; 64];
        let mut offset = 0usize;
        {
            let bytes = self.name.as_bytes();
            let len = bytes.len().min(20);
            buf[offset..offset + len].copy_from_slice(&bytes[..len]);
            // remaining bytes stay zero
            offset += 20;
        }
        buf[offset..offset + 4].copy_from_slice(&self.encoder_steps_per_mm.to_le_bytes());
        offset += 4;
        buf[offset..offset + 4].copy_from_slice(&self.servo_steps_per_mm.to_le_bytes());
        offset += 4;
        buf[offset..offset + 4].copy_from_slice(&self.force_gauge_n_per_step.to_le_bytes());
        offset += 4;
        buf[offset..offset + 4].copy_from_slice(&self.force_gauge_zero_offset.to_le_bytes());
        offset += 4;
        buf[offset..offset + 4].copy_from_slice(&self.max_position.to_le_bytes());
        offset += 4;
        buf[offset..offset + 4].copy_from_slice(&self.max_velocity.to_le_bytes());
        offset += 4;
        buf[offset..offset + 4].copy_from_slice(&self.max_acceleration.to_le_bytes());
        offset += 4;
        buf[offset..offset + 4].copy_from_slice(&self.max_force_tensile.to_le_bytes());
        offset += 4;
        buf[offset..offset + 4].copy_from_slice(&self.homing_velocity.to_le_bytes());
        offset += 4;
        buf[offset..offset + 4].copy_from_slice(&self.homing_offset.to_le_bytes());
        offset += 4;
        buf[offset..offset + 4].copy_from_slice(&self.jaw_offset.to_le_bytes());
        offset += 4;
        let _ = offset; // suppress unused warning
        buf
    }

    /// Decode from wire bytes.
    /// Output values are in the agreed `unit`; scale divided during bit unpacking.
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < 64 {
            return None;
        }
        let mut offset = 0usize;
        let name = {
            let slice = &buf[offset..offset + 20];
            let end = slice.iter().position(|&b| b == 0).unwrap_or(20);
            String::from_utf8_lossy(&slice[..end]).into_owned()
        };
        offset += 20;
        let encoder_steps_per_mm = i32::from_le_bytes(buf[offset..offset + 4].try_into().ok()?);
        offset += 4;
        let servo_steps_per_mm = i32::from_le_bytes(buf[offset..offset + 4].try_into().ok()?);
        offset += 4;
        let force_gauge_n_per_step = i32::from_le_bytes(buf[offset..offset + 4].try_into().ok()?);
        offset += 4;
        let force_gauge_zero_offset = i32::from_le_bytes(buf[offset..offset + 4].try_into().ok()?);
        offset += 4;
        let max_position = i32::from_le_bytes(buf[offset..offset + 4].try_into().ok()?);
        offset += 4;
        let max_velocity = i32::from_le_bytes(buf[offset..offset + 4].try_into().ok()?);
        offset += 4;
        let max_acceleration = i32::from_le_bytes(buf[offset..offset + 4].try_into().ok()?);
        offset += 4;
        let max_force_tensile = i32::from_le_bytes(buf[offset..offset + 4].try_into().ok()?);
        offset += 4;
        let homing_velocity = i32::from_le_bytes(buf[offset..offset + 4].try_into().ok()?);
        offset += 4;
        let homing_offset = i32::from_le_bytes(buf[offset..offset + 4].try_into().ok()?);
        offset += 4;
        let jaw_offset = i32::from_le_bytes(buf[offset..offset + 4].try_into().ok()?);
        offset += 4;
        let _ = offset; // suppress unused warning

        Some(Self {
            name,
            encoder_steps_per_mm,
            servo_steps_per_mm,
            force_gauge_n_per_step,
            force_gauge_zero_offset,
            max_position,
            max_velocity,
            max_acceleration,
            max_force_tensile,
            homing_velocity,
            homing_offset,
            jaw_offset,
        })
    }
}

/// Sample profile — material test limits (aligned, 20 bytes on wire)
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SampleProfile {
    pub max_force: u32,
    pub max_velocity: u32,
    pub max_displacement: u32,
    pub sample_width: u32,
    pub sample_thickness: u32,
}

impl SampleProfile {
    pub const WIRE_SIZE: usize = 20;

    /// Encode to wire bytes (20 bytes).
    /// Input values are in the agreed `unit`; scale multiplied during bit packing.
    pub fn encode(&self) -> [u8; 20] {
        let mut buf = [0u8; 20];
        let mut offset = 0usize;
        buf[offset..offset + 4].copy_from_slice(&self.max_force.to_le_bytes());
        offset += 4;
        buf[offset..offset + 4].copy_from_slice(&self.max_velocity.to_le_bytes());
        offset += 4;
        buf[offset..offset + 4].copy_from_slice(&self.max_displacement.to_le_bytes());
        offset += 4;
        buf[offset..offset + 4].copy_from_slice(&self.sample_width.to_le_bytes());
        offset += 4;
        buf[offset..offset + 4].copy_from_slice(&self.sample_thickness.to_le_bytes());
        offset += 4;
        let _ = offset; // suppress unused warning
        buf
    }

    /// Decode from wire bytes.
    /// Output values are in the agreed `unit`; scale divided during bit unpacking.
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < 20 {
            return None;
        }
        let mut offset = 0usize;
        let max_force = u32::from_le_bytes(buf[offset..offset + 4].try_into().ok()?);
        offset += 4;
        let max_velocity = u32::from_le_bytes(buf[offset..offset + 4].try_into().ok()?);
        offset += 4;
        let max_displacement = u32::from_le_bytes(buf[offset..offset + 4].try_into().ok()?);
        offset += 4;
        let sample_width = u32::from_le_bytes(buf[offset..offset + 4].try_into().ok()?);
        offset += 4;
        let sample_thickness = u32::from_le_bytes(buf[offset..offset + 4].try_into().ok()?);
        offset += 4;
        let _ = offset; // suppress unused warning

        Some(Self {
            max_force,
            max_velocity,
            max_displacement,
            sample_width,
            sample_thickness,
        })
    }
}

/// Firmware version string (aligned, 16 bytes on wire)
#[derive(Debug, Clone, Default, PartialEq)]
pub struct FirmwareVersion {
    pub version: String,
}

impl FirmwareVersion {
    pub const WIRE_SIZE: usize = 16;

    /// Encode to wire bytes (16 bytes).
    /// Input values are in the agreed `unit`; scale multiplied during bit packing.
    pub fn encode(&self) -> [u8; 16] {
        let mut buf = [0u8; 16];
        let mut offset = 0usize;
        {
            let bytes = self.version.as_bytes();
            let len = bytes.len().min(16);
            buf[offset..offset + len].copy_from_slice(&bytes[..len]);
            // remaining bytes stay zero
            offset += 16;
        }
        let _ = offset; // suppress unused warning
        buf
    }

    /// Decode from wire bytes.
    /// Output values are in the agreed `unit`; scale divided during bit unpacking.
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < 16 {
            return None;
        }
        let mut offset = 0usize;
        let version = {
            let slice = &buf[offset..offset + 16];
            let end = slice.iter().position(|&b| b == 0).unwrap_or(16);
            String::from_utf8_lossy(&slice[..end]).into_owned()
        };
        offset += 16;
        let _ = offset; // suppress unused warning

        Some(Self {
            version,
        })
    }
}

/// Test run command — references uploaded G-code and assigns test data ID (aligned, 14 bytes on wire)
#[derive(Debug, Clone, Default, PartialEq)]
pub struct TestRun {
    pub gcode_id: String,
    pub test_data_id: String,
}

impl TestRun {
    pub const WIRE_SIZE: usize = 14;

    /// Encode to wire bytes (14 bytes).
    /// Input values are in the agreed `unit`; scale multiplied during bit packing.
    pub fn encode(&self) -> [u8; 14] {
        let mut buf = [0u8; 14];
        let mut offset = 0usize;
        {
            let bytes = self.gcode_id.as_bytes();
            let len = bytes.len().min(7);
            buf[offset..offset + len].copy_from_slice(&bytes[..len]);
            // remaining bytes stay zero
            offset += 7;
        }
        {
            let bytes = self.test_data_id.as_bytes();
            let len = bytes.len().min(7);
            buf[offset..offset + len].copy_from_slice(&bytes[..len]);
            // remaining bytes stay zero
            offset += 7;
        }
        let _ = offset; // suppress unused warning
        buf
    }

    /// Decode from wire bytes.
    /// Output values are in the agreed `unit`; scale divided during bit unpacking.
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < 14 {
            return None;
        }
        let mut offset = 0usize;
        let gcode_id = {
            let slice = &buf[offset..offset + 7];
            let end = slice.iter().position(|&b| b == 0).unwrap_or(7);
            String::from_utf8_lossy(&slice[..end]).into_owned()
        };
        offset += 7;
        let test_data_id = {
            let slice = &buf[offset..offset + 7];
            let end = slice.iter().position(|&b| b == 0).unwrap_or(7);
            String::from_utf8_lossy(&slice[..end]).into_owned()
        };
        offset += 7;
        let _ = offset; // suppress unused warning

        Some(Self {
            gcode_id,
            test_data_id,
        })
    }
}

/// Firmware notification message (aligned, 101 bytes on wire)
#[derive(Debug, Clone, Default, PartialEq)]
pub struct Notification {
    pub r#type: NotificationType,
    pub message: String,
}

impl Notification {
    pub const WIRE_SIZE: usize = 101;

    /// Encode to wire bytes (101 bytes).
    /// Input values are in the agreed `unit`; scale multiplied during bit packing.
    pub fn encode(&self) -> [u8; 101] {
        let mut buf = [0u8; 101];
        let mut offset = 0usize;
        buf[offset] = self.r#type.to_wire();
        offset += 1;
        {
            let bytes = self.message.as_bytes();
            let len = bytes.len().min(100);
            buf[offset..offset + len].copy_from_slice(&bytes[..len]);
            // remaining bytes stay zero
            offset += 100;
        }
        let _ = offset; // suppress unused warning
        buf
    }

    /// Decode from wire bytes.
    /// Output values are in the agreed `unit`; scale divided during bit unpacking.
    pub fn decode(buf: &[u8]) -> Option<Self> {
        if buf.len() < 101 {
            return None;
        }
        let mut offset = 0usize;
        let r#type = NotificationType::from_wire(buf[offset]).unwrap_or_default();
        offset += 1;
        let message = {
            let slice = &buf[offset..offset + 100];
            let end = slice.iter().position(|&b| b == 0).unwrap_or(100);
            String::from_utf8_lossy(&slice[..end]).into_owned()
        };
        offset += 100;
        let _ = offset; // suppress unused warning

        Some(Self {
            r#type,
            message,
        })
    }
}

// ============================================================
// Message Command IDs
// ============================================================
pub const MSG_READ_SAMPLE: u8 = 0;
pub const MSG_READ_STATE: u8 = 1;
pub const MSG_READ_MACHINE_CONFIGURATION: u8 = 2;
pub const MSG_READ_FIRMWARE_VERSION: u8 = 3;
pub const MSG_READ_SAMPLE_PROFILE: u8 = 4;
pub const MSG_WRITE_MACHINE_CONFIGURATION_WRITE: u8 = 0;
pub const MSG_WRITE_MOTION_ENABLE: u8 = 1;
pub const MSG_WRITE_TEST_RUN: u8 = 2;
pub const MSG_WRITE_MANUAL_MOVE: u8 = 3;
pub const MSG_WRITE_TEST_MOVE: u8 = 4;
pub const MSG_WRITE_TEST_WAVEFORM: u8 = 8;
pub const MSG_WRITE_SAMPLE_PROFILE_WRITE: u8 = 5;
pub const MSG_WRITE_GAUGE_LENGTH: u8 = 6;
pub const MSG_WRITE_GAUGE_FORCE: u8 = 7;
pub const MSG_WRITE_FILE_DOWNLOAD: u8 = 9;

// ============================================================
// Periodic Message Periods
// ============================================================
pub const MSG_SAMPLE_PERIOD_MS: u32 = 10;
pub const MSG_STATE_PERIOD_MS: u32 = 1000;

// ============================================================
// Message Priorities (host scheduling hint; not on the wire)
// ============================================================
pub const MSG_SAMPLE_PRIORITY: &str = "low";
pub const MSG_STATE_PRIORITY: &str = "low";
pub const MSG_MACHINE_CONFIGURATION_PRIORITY: &str = "high";
pub const MSG_FIRMWARE_VERSION_PRIORITY: &str = "high";
pub const MSG_SAMPLE_PROFILE_PRIORITY: &str = "high";
pub const MSG_MACHINE_CONFIGURATION_WRITE_PRIORITY: &str = "high";
pub const MSG_MOTION_ENABLE_PRIORITY: &str = "high";
pub const MSG_TEST_RUN_PRIORITY: &str = "high";
pub const MSG_MANUAL_MOVE_PRIORITY: &str = "high";
pub const MSG_TEST_MOVE_PRIORITY: &str = "high";
pub const MSG_TEST_WAVEFORM_PRIORITY: &str = "high";
pub const MSG_SAMPLE_PROFILE_WRITE_PRIORITY: &str = "high";
pub const MSG_GAUGE_LENGTH_PRIORITY: &str = "high";
pub const MSG_GAUGE_FORCE_PRIORITY: &str = "high";
pub const MSG_FILE_DOWNLOAD_PRIORITY: &str = "high";

// ============================================================
// Typed message facade
// ============================================================
// Bridges the generic runtime (raw command id + payload bytes) to typed,
// decoded payloads — the "last mile" so callers don't hand-map ids to structs.

/// A decoded inbound payload (a DATA response or an async notification),
/// tagged with the message it belongs to.
#[derive(Debug, Clone, PartialEq)]
pub enum Inbound {
    /// DATA response for `sample` (command 0).
    Sample(Sample),
    /// DATA response for `state` (command 1).
    State(MachineState),
    /// DATA response for `machine_configuration` (command 2).
    MachineConfiguration(MachineConfiguration),
    /// DATA response for `firmware_version` (command 3).
    FirmwareVersion(FirmwareVersion),
    /// DATA response for `sample_profile` (command 4).
    SampleProfile(SampleProfile),
    /// DATA response for `file_download` (command 9).
    FileDownload(StoredSample),
    /// Async `notification` notification.
    Notification(Notification),
    /// Command not recognized as a DATA producer — raw bytes preserved.
    Unknown { command: u8, payload: Vec<u8> },
}

impl Inbound {
    /// Decode a DATA response for `command` into its typed payload. Unknown
    /// commands and decode failures yield [`Inbound::Unknown`].
    pub fn decode_data(command: u8, payload: &[u8]) -> Self {
        match command {
            0 => Sample::decode(payload)
                .map(Inbound::Sample)
                .unwrap_or_else(|| Inbound::Unknown { command, payload: payload.to_vec() }),
            1 => MachineState::decode(payload)
                .map(Inbound::State)
                .unwrap_or_else(|| Inbound::Unknown { command, payload: payload.to_vec() }),
            2 => MachineConfiguration::decode(payload)
                .map(Inbound::MachineConfiguration)
                .unwrap_or_else(|| Inbound::Unknown { command, payload: payload.to_vec() }),
            3 => FirmwareVersion::decode(payload)
                .map(Inbound::FirmwareVersion)
                .unwrap_or_else(|| Inbound::Unknown { command, payload: payload.to_vec() }),
            4 => SampleProfile::decode(payload)
                .map(Inbound::SampleProfile)
                .unwrap_or_else(|| Inbound::Unknown { command, payload: payload.to_vec() }),
            9 => StoredSample::decode(payload)
                .map(Inbound::FileDownload)
                .unwrap_or_else(|| Inbound::Unknown { command, payload: payload.to_vec() }),
            _ => Inbound::Unknown { command, payload: payload.to_vec() },
        }
    }

    /// Decode an async `notification` notification payload into its typed struct.
    pub fn decode_notification(payload: &[u8]) -> Option<Notification> {
        Notification::decode(payload)
    }
}

// ============================================================
// Bit Packing Helpers
// ============================================================

/// Write `bits` bits from `value` into `buf` starting at `bit_off`. LSB-first.
fn pack_bits(buf: &mut [u8], bit_off: u32, bits: u32, value: u32) {
    for i in 0..bits {
        let byte_idx = ((bit_off + i) / 8) as usize;
        let bit_idx = (bit_off + i) % 8;
        if (value >> i) & 1 != 0 {
            buf[byte_idx] |= 1 << bit_idx;
        }
    }
}

/// Read `bits` bits from `buf` starting at `bit_off`. LSB-first. Returns unsigned.
fn unpack_bits(buf: &[u8], bit_off: u32, bits: u32) -> u32 {
    let mut value: u32 = 0;
    for i in 0..bits {
        let byte_idx = ((bit_off + i) / 8) as usize;
        let bit_idx = (bit_off + i) % 8;
        if (buf[byte_idx] >> bit_idx) & 1 != 0 {
            value |= 1 << i;
        }
    }
    value
}

// ============================================================
// Tests
// ============================================================
#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_machine_state_roundtrip() {
        #[allow(unused_mut)]
        let mut original = MachineState::default();
        let encoded = original.encode();
        assert_eq!(encoded.len(), 2);
        let decoded = MachineState::decode(&encoded).expect("decode failed");
        // Verify a valid in-range instance roundtrips
        assert_eq!(decoded.faulted_reason, original.faulted_reason);
        assert_eq!(decoded.restricted_reason, original.restricted_reason);
        assert_eq!(decoded.test_running, original.test_running);
        assert_eq!(decoded.motion_enabled, original.motion_enabled);
    }

    #[test]
    fn test_sample_roundtrip() {
        #[allow(unused_mut)]
        let mut original = Sample::default();
        let encoded = original.encode();
        assert_eq!(encoded.len(), 12);
        let decoded = Sample::decode(&encoded).expect("decode failed");
        // Verify a valid in-range instance roundtrips
        assert_eq!(decoded.machine_force, original.machine_force);
        assert_eq!(decoded.machine_position, original.machine_position);
        assert_eq!(decoded.machine_setpoint, original.machine_setpoint);
        assert_eq!(decoded.sample_force, original.sample_force);
        assert_eq!(decoded.sample_position, original.sample_position);
    }

    #[test]
    fn test_move_roundtrip() {
        #[allow(unused_mut)]
        let mut original = Move::default();
        let encoded = original.encode();
        assert_eq!(encoded.len(), 8);
        let decoded = Move::decode(&encoded).expect("decode failed");
        // Verify a valid in-range instance roundtrips
        assert_eq!(decoded.g, original.g);
        assert_eq!(decoded.x, original.x);
        assert_eq!(decoded.f, original.f);
        assert_eq!(decoded.p, original.p);
    }

    #[test]
    fn test_waveform_move_roundtrip() {
        #[allow(unused_mut)]
        let mut original = WaveformMove::default();
        // `cycles` is range-constrained to [1, 10000000]: Default 0 is outside the packed range, so seed the in-range min.
        original.cycles = 1;
        let encoded = original.encode();
        assert_eq!(encoded.len(), 9);
        let decoded = WaveformMove::decode(&encoded).expect("decode failed");
        // Verify a valid in-range instance roundtrips
        assert_eq!(decoded.shape, original.shape);
        assert_eq!(decoded.amplitude, original.amplitude);
        assert_eq!(decoded.frequency, original.frequency);
        assert_eq!(decoded.cycles, original.cycles);
    }

    #[test]
    fn test_stored_sample_roundtrip() {
        #[allow(unused_mut)]
        let mut original = StoredSample::default();
        let encoded = original.encode();
        assert_eq!(encoded.len(), 11);
        let decoded = StoredSample::decode(&encoded).expect("decode failed");
        // Verify a valid in-range instance roundtrips
        assert_eq!(decoded.force, original.force);
        assert_eq!(decoded.position, original.position);
        assert_eq!(decoded.time, original.time);
        assert_eq!(decoded.setpoint, original.setpoint);
    }

    #[test]
    fn test_machine_configuration_roundtrip() {
        #[allow(unused_mut)]
        let mut original = MachineConfiguration::default();
        let encoded = original.encode();
        assert_eq!(encoded.len(), 64);
        let decoded = MachineConfiguration::decode(&encoded).expect("decode failed");
        // Verify a valid in-range instance roundtrips
        assert_eq!(decoded.name, original.name);
        assert_eq!(decoded.encoder_steps_per_mm, original.encoder_steps_per_mm);
        assert_eq!(decoded.servo_steps_per_mm, original.servo_steps_per_mm);
        assert_eq!(decoded.force_gauge_n_per_step, original.force_gauge_n_per_step);
        assert_eq!(decoded.force_gauge_zero_offset, original.force_gauge_zero_offset);
        assert_eq!(decoded.max_position, original.max_position);
        assert_eq!(decoded.max_velocity, original.max_velocity);
        assert_eq!(decoded.max_acceleration, original.max_acceleration);
        assert_eq!(decoded.max_force_tensile, original.max_force_tensile);
        assert_eq!(decoded.homing_velocity, original.homing_velocity);
        assert_eq!(decoded.homing_offset, original.homing_offset);
        assert_eq!(decoded.jaw_offset, original.jaw_offset);
    }

    #[test]
    fn test_sample_profile_roundtrip() {
        #[allow(unused_mut)]
        let mut original = SampleProfile::default();
        let encoded = original.encode();
        assert_eq!(encoded.len(), 20);
        let decoded = SampleProfile::decode(&encoded).expect("decode failed");
        // Verify a valid in-range instance roundtrips
        assert_eq!(decoded.max_force, original.max_force);
        assert_eq!(decoded.max_velocity, original.max_velocity);
        assert_eq!(decoded.max_displacement, original.max_displacement);
        assert_eq!(decoded.sample_width, original.sample_width);
        assert_eq!(decoded.sample_thickness, original.sample_thickness);
    }

    #[test]
    fn test_firmware_version_roundtrip() {
        #[allow(unused_mut)]
        let mut original = FirmwareVersion::default();
        let encoded = original.encode();
        assert_eq!(encoded.len(), 16);
        let decoded = FirmwareVersion::decode(&encoded).expect("decode failed");
        // Verify a valid in-range instance roundtrips
        assert_eq!(decoded.version, original.version);
    }

    #[test]
    fn test_test_run_roundtrip() {
        #[allow(unused_mut)]
        let mut original = TestRun::default();
        let encoded = original.encode();
        assert_eq!(encoded.len(), 14);
        let decoded = TestRun::decode(&encoded).expect("decode failed");
        // Verify a valid in-range instance roundtrips
        assert_eq!(decoded.gcode_id, original.gcode_id);
        assert_eq!(decoded.test_data_id, original.test_data_id);
    }

    #[test]
    fn test_notification_roundtrip() {
        #[allow(unused_mut)]
        let mut original = Notification::default();
        let encoded = original.encode();
        assert_eq!(encoded.len(), 101);
        let decoded = Notification::decode(&encoded).expect("decode failed");
        // Verify a valid in-range instance roundtrips
        assert_eq!(decoded.r#type, original.r#type);
        assert_eq!(decoded.message, original.message);
    }

    #[test]
    fn test_faulted_reason_wire_roundtrip() {
        for i in 0..9u8 {
            let e = FaultedReason::from_wire(i).expect("valid wire index");
            assert_eq!(e.to_wire(), i);
        }
        // Out of range returns None
        assert!(FaultedReason::from_wire(9).is_none());
    }

    #[test]
    fn test_restricted_reason_wire_roundtrip() {
        for i in 0..7u8 {
            let e = RestrictedReason::from_wire(i).expect("valid wire index");
            assert_eq!(e.to_wire(), i);
        }
        // Out of range returns None
        assert!(RestrictedReason::from_wire(7).is_none());
    }

    #[test]
    fn test_motion_state_wire_roundtrip() {
        for i in 0..3u8 {
            let e = MotionState::from_wire(i).expect("valid wire index");
            assert_eq!(e.to_wire(), i);
        }
        // Out of range returns None
        assert!(MotionState::from_wire(3).is_none());
    }

    #[test]
    fn test_g_code_wire_roundtrip() {
        for i in 0..10u8 {
            let e = GCode::from_wire(i).expect("valid wire index");
            assert_eq!(e.to_wire(), i);
        }
        // Out of range returns None
        assert!(GCode::from_wire(10).is_none());
    }

    #[test]
    fn test_g_code_value_remap() {
        assert_eq!(GCode::from_value(0).unwrap(), GCode::RapidMove);
        assert_eq!(GCode::RapidMove.to_value(), 0);
        assert_eq!(GCode::from_value(1).unwrap(), GCode::LinearMove);
        assert_eq!(GCode::LinearMove.to_value(), 1);
        assert_eq!(GCode::from_value(2).unwrap(), GCode::CwArc);
        assert_eq!(GCode::CwArc.to_value(), 2);
        assert_eq!(GCode::from_value(3).unwrap(), GCode::CcwArc);
        assert_eq!(GCode::CcwArc.to_value(), 3);
        assert_eq!(GCode::from_value(4).unwrap(), GCode::Dwell);
        assert_eq!(GCode::Dwell.to_value(), 4);
        assert_eq!(GCode::from_value(28).unwrap(), GCode::Home);
        assert_eq!(GCode::Home.to_value(), 28);
        assert_eq!(GCode::from_value(90).unwrap(), GCode::Absolute);
        assert_eq!(GCode::Absolute.to_value(), 90);
        assert_eq!(GCode::from_value(91).unwrap(), GCode::Incremental);
        assert_eq!(GCode::Incremental.to_value(), 91);
        assert_eq!(GCode::from_value(122).unwrap(), GCode::Stop);
        assert_eq!(GCode::Stop.to_value(), 122);
        assert_eq!(GCode::from_value(123).unwrap(), GCode::Waveform);
        assert_eq!(GCode::Waveform.to_value(), 123);
    }
    #[test]
    fn test_waveform_shape_wire_roundtrip() {
        for i in 0..2u8 {
            let e = WaveformShape::from_wire(i).expect("valid wire index");
            assert_eq!(e.to_wire(), i);
        }
        // Out of range returns None
        assert!(WaveformShape::from_wire(2).is_none());
    }

    #[test]
    fn test_notification_type_wire_roundtrip() {
        for i in 0..5u8 {
            let e = NotificationType::from_wire(i).expect("valid wire index");
            assert_eq!(e.to_wire(), i);
        }
        // Out of range returns None
        assert!(NotificationType::from_wire(5).is_none());
    }

    #[test]
    fn test_logging_state_wire_roundtrip() {
        for i in 0..3u8 {
            let e = LoggingState::from_wire(i).expect("valid wire index");
            assert_eq!(e.to_wire(), i);
        }
        // Out of range returns None
        assert!(LoggingState::from_wire(3).is_none());
    }


    // Typed facade: a DATA response must decode back to the right variant.
    #[test]
    fn test_facade_sample_decode_data() {
        let original = Sample::default();
        let bytes = original.encode();
        match Inbound::decode_data(0, &bytes) {
            Inbound::Sample(v) => assert_eq!(v, original),
            other => panic!("expected Sample, got {:?}", other),
        }
    }
    #[test]
    fn test_facade_state_decode_data() {
        let original = MachineState::default();
        let bytes = original.encode();
        match Inbound::decode_data(1, &bytes) {
            Inbound::State(v) => assert_eq!(v, original),
            other => panic!("expected State, got {:?}", other),
        }
    }
    #[test]
    fn test_facade_machine_configuration_decode_data() {
        let original = MachineConfiguration::default();
        let bytes = original.encode();
        match Inbound::decode_data(2, &bytes) {
            Inbound::MachineConfiguration(v) => assert_eq!(v, original),
            other => panic!("expected MachineConfiguration, got {:?}", other),
        }
    }
    #[test]
    fn test_facade_firmware_version_decode_data() {
        let original = FirmwareVersion::default();
        let bytes = original.encode();
        match Inbound::decode_data(3, &bytes) {
            Inbound::FirmwareVersion(v) => assert_eq!(v, original),
            other => panic!("expected FirmwareVersion, got {:?}", other),
        }
    }
    #[test]
    fn test_facade_sample_profile_decode_data() {
        let original = SampleProfile::default();
        let bytes = original.encode();
        match Inbound::decode_data(4, &bytes) {
            Inbound::SampleProfile(v) => assert_eq!(v, original),
            other => panic!("expected SampleProfile, got {:?}", other),
        }
    }
    #[test]
    fn test_facade_file_download_decode_data() {
        let original = StoredSample::default();
        let bytes = original.encode();
        match Inbound::decode_data(9, &bytes) {
            Inbound::FileDownload(v) => assert_eq!(v, original),
            other => panic!("expected FileDownload, got {:?}", other),
        }
    }
}
