name: Build MaD Firmware

on:
  push:
    branches: 
      - "main"
    paths:
      - 'Firmware/**'
    tags:
      - 'firmware-v*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Firmware/**'

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install PlatformIO Core
      run: pip install --upgrade platformio
    - name: Install propeller platformio platform
      working-directory: Firmware/MaDCore
      run: pio pkg install --platform https://github.com/RileyMcCarthy/platform-propeller.git
    - name: Extract version from tag
      id: get_version
      run: |
        if [[ $GITHUB_REF == refs/tags/firmware-v* ]]; then
          # If building from a firmware tag, extract the version number
          VERSION=${GITHUB_REF#refs/tags/firmware-v}
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Using version from tag: $VERSION"
        else
          # Default version for non-tag builds
          echo "VERSION=dev" >> $GITHUB_OUTPUT
          echo "Using default version: dev"
        fi
    - name: Build Firmware - Debug Version
      working-directory: Firmware/MaDCore
      run: pio run -e propeller2_debug --program-arg="-DFIRMWARE_VERSION=\"${{ steps.get_version.outputs.VERSION }}\""
    - name: Build Firmware - Release Version
      working-directory: Firmware/MaDCore
      run: pio run -e propeller2_release --program-arg="-DFIRMWARE_VERSION=\"${{ steps.get_version.outputs.VERSION }}\""
    - name: Copy and rename build artifacts
      run: |
        mkdir -p release-assets
        # Copy debug version with .bin extension
        cp Firmware/MaDCore/.pio/build/propeller2_debug/program release-assets/MaD-Firmware-${{ steps.get_version.outputs.VERSION }}-debug.bin
        # Copy release version with .bin extension
        cp Firmware/MaDCore/.pio/build/propeller2_release/program release-assets/MaD-Firmware-${{ steps.get_version.outputs.VERSION }}-release.bin
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MaD-Firmware-${{ github.run_number }}
        path: release-assets/

  create-release:
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/firmware-v')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Display structure of downloaded files
        run: ls -R artifacts
          
      - name: Get tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/firmware-}" >> $GITHUB_OUTPUT
      
      - name: Copy firmware files to release folder
        run: |
          mkdir -p release
          cp artifacts/MaD-Firmware-*/*.bin release/
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: MaD Firmware ${{ steps.get_version.outputs.VERSION }}
          tag_name: firmware-${{ steps.get_version.outputs.VERSION }}
          files: release/*.bin
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 