name: Build MaD Hardware

on:
  push:
    branches: 
      - "main"
    tags:
      - 'hardware-v*'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'Hardware/**'

permissions:
  contents: write
  packages: write

jobs:
  build-hardware:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - project: EdgeBoard
            pcb_path: Hardware/EdgeBoard/KiCad/MaD_Edge.kicad_pcb
            sch_path: Hardware/EdgeBoard/KiCad/MaD_Edge.kicad_sch
          - project: DS2Addon
            pcb_path: Hardware/DS2Addon/KICAD/DS2_Addon.kicad_pcb
            sch_path: Hardware/DS2Addon/KICAD/DS2_Addon.kicad_sch

    steps:
    - uses: actions/checkout@v4
    
    - name: Generate manufacturing files using KiBot
      uses: INTI-CMNB/KiBot@v2_k7
      with:
        config: .kibot/config.kibot.yaml
        board: ${{ matrix.pcb_path }}
        schema: ${{ matrix.sch_path }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.project }}-hardware-${{ github.run_number }}
        path: |
          Hardware/${{ matrix.project }}/Manufacturing/
          Hardware/${{ matrix.project }}/Documentation/

  create-release:
    needs: [build-hardware]
    if: startsWith(github.ref, 'refs/tags/hardware-v')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          
      - name: Get tag version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/hardware-}" >> $GITHUB_OUTPUT
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: MaD Hardware ${{ steps.get_version.outputs.VERSION }}
          tag_name: hardware-${{ steps.get_version.outputs.VERSION }}
          files: artifacts/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 