name: Build Software

on:
  push:
    branches: [main]
    tags:
      - 'software-v*'
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest-large

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
        
      - name: Ensure Python distutils is available
        run: |
          python3 -m pip install --upgrade pip setuptools --break-system-packages

      - name: Install dependencies
        working-directory: Software/MaDControl
        run: npm install
    
      - name: Build application
        working-directory: Software/MaDControl
        run: |
          npm run build:dll
          npm run build
          if [[ $GITHUB_REF == refs/tags/software-v* ]]; then
            echo "Building from tag - will publish to GitHub releases"
            npm exec electron-builder -- --publish onTag --win --mac --linux
          else
            echo "Building from push - will create artifacts only"
            npm exec electron-builder -- --publish never --win --mac --linux
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload build artifacts (for non-tag builds)
        if: ${{ !startsWith(github.ref, 'refs/tags/software-v') }}
        uses: actions/upload-artifact@v4
        with:
          name: MaD-Control-${{ github.run_number }}
          path: |
            Software/MaDControl/release/build/*.dmg
            Software/MaDControl/release/build/*.zip
            Software/MaDControl/release/build/*.exe
            Software/MaDControl/release/build/*.AppImage
            Software/MaDControl/release/build/*.deb 