name: Build Software

on:
  push:
    branches: [main]
    tags:
      - 'software-v*'
  pull_request:
    branches: [main]
    paths:
      - 'Software/**'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4

      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        working-directory: Software/MaDControl
        run: npm install
    
      - name: Ensure Python distutils is available
        run: |
          python3 -m pip install --upgrade pip setuptools
          python3 -m pip install setuptools

      - name: Build application
        working-directory: Software/MaDControl
        run: |
          npm run build:dll
          npm run build
          npm exec electron-builder -- --publish always --win --mac --linux
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} 